package server

import (
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"go.uber.org/zap"
)

const installScriptTemplate = `#!/usr/bin/env bash
# Control One Agent Installer
# Generated by the Control One control plane.
set -euo pipefail

# ─── Colors ─────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fatal() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ─── Baked-in values from control plane ─────────────────────────────
CONTROL_PLANE_URL="${CONTROL_PLANE_URL:-{{.CPURL}}}"
TOKEN="${TOKEN:-{{.Token}}}"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
NO_SERVICE="${NO_SERVICE:-false}"

# ─── Parse arguments ────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --token)      TOKEN="$2"; shift 2 ;;
        --url)        CONTROL_PLANE_URL="$2"; shift 2 ;;
        --install-dir) INSTALL_DIR="$2"; shift 2 ;;
        --no-service) NO_SERVICE="true"; shift ;;
        -h|--help)
            echo "Usage: $0 [--token TOKEN] [--url URL] [--install-dir DIR] [--no-service]"
            exit 0 ;;
        *) fatal "Unknown argument: $1" ;;
    esac
done

[[ -z "$CONTROL_PLANE_URL" ]] && fatal "CONTROL_PLANE_URL is required."
[[ -z "$TOKEN" ]] && fatal "TOKEN is required."

CONTROL_PLANE_URL="${CONTROL_PLANE_URL%/}"

# ─── Detect platform ────────────────────────────────────────────────
detect_os() {
    local os; os="$(uname -s | tr '[:upper:]' '[:lower:]')"
    case "$os" in
        linux)  echo "linux" ;;
        darwin) echo "darwin" ;;
        *)      fatal "Unsupported OS: $os" ;;
    esac
}

detect_arch() {
    local arch; arch="$(uname -m)"
    case "$arch" in
        x86_64|amd64)  echo "amd64" ;;
        aarch64|arm64) echo "arm64" ;;
        *)             fatal "Unsupported arch: $arch" ;;
    esac
}

OS="$(detect_os)"
ARCH="$(detect_arch)"
info "Platform: ${OS}/${ARCH}"

command -v curl >/dev/null 2>&1 || fatal "curl is required."

SUDO=""
if [[ "$EUID" -ne 0 ]]; then
    command -v sudo >/dev/null 2>&1 && SUDO="sudo" || warn "Not root and no sudo."
fi

TMP_DIR="$(mktemp -d)"
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

BINARY_URL="${CONTROL_PLANE_URL}/api/v1/agent/binary?os=${OS}&arch=${ARCH}"
BINARY_PATH="${TMP_DIR}/controlone-agent"

info "Downloading agent binary..."
HTTP_CODE=$(curl -fsSL -w "%%{http_code}" -o "$BINARY_PATH" "$BINARY_URL" 2>/dev/null) || true

[[ ! -f "$BINARY_PATH" ]] || [[ ! -s "$BINARY_PATH" ]] && fatal "Download failed (HTTP ${HTTP_CODE:-???})."
[[ "${HTTP_CODE}" != "200" ]] && fatal "Unexpected HTTP ${HTTP_CODE}."

ok "Binary downloaded."

$SUDO mkdir -p "$INSTALL_DIR"
$SUDO install -m 0755 "$BINARY_PATH" "${INSTALL_DIR}/controlone-agent"
ok "Installed to ${INSTALL_DIR}/controlone-agent."

ENROLL_ARGS=("--join" "$CONTROL_PLANE_URL" "--token" "$TOKEN")
[[ "$NO_SERVICE" != "true" ]] && ENROLL_ARGS+=("--install-service")

info "Enrolling agent..."
$SUDO "${INSTALL_DIR}/controlone-agent" "${ENROLL_ARGS[@]}" || fatal "Enrollment failed."

ok "Control One agent installation complete!"
`

// installScriptPowerShellTemplate is the Windows analogue of the bash installer.
// It uses PowerShell 5.1+ built-ins only (Invoke-WebRequest, $env:PROCESSOR_ARCHITECTURE)
// so the one-liner `iwr ... | iex` works on a stock Windows Server / Windows 10+ host.
const installScriptPowerShellTemplate = `# Control One Agent Installer (PowerShell)
# Generated by the Control One control plane.
$ErrorActionPreference = 'Stop'

function Write-Info  { param($m) Write-Host "[INFO]  $m" -ForegroundColor Cyan }
function Write-Ok    { param($m) Write-Host "[OK]    $m" -ForegroundColor Green }
function Write-Warn2 { param($m) Write-Host "[WARN]  $m" -ForegroundColor Yellow }
function Die         { param($m) Write-Host "[ERROR] $m" -ForegroundColor Red; exit 1 }

# ─── Baked-in values from control plane ─────────────────────────────
if (-not $env:CONTROL_PLANE_URL) { $env:CONTROL_PLANE_URL = '{{.CPURL}}' }
if (-not $env:TOKEN)             { $env:TOKEN             = '{{.Token}}' }
if (-not $env:INSTALL_DIR)       { $env:INSTALL_DIR       = 'C:\Program Files\ControlOne' }
if (-not $env:NO_SERVICE)        { $env:NO_SERVICE        = 'false' }

# ─── Parse arguments ────────────────────────────────────────────────
for ($i = 0; $i -lt $args.Count; $i++) {
    switch ($args[$i]) {
        '--token'       { $env:TOKEN             = $args[$i+1]; $i++ }
        '--url'         { $env:CONTROL_PLANE_URL = $args[$i+1]; $i++ }
        '--install-dir' { $env:INSTALL_DIR       = $args[$i+1]; $i++ }
        '--no-service'  { $env:NO_SERVICE        = 'true' }
        '-h'            { Write-Host "Usage: install-agent.ps1 [--token TOKEN] [--url URL] [--install-dir DIR] [--no-service]"; exit 0 }
        '--help'        { Write-Host "Usage: install-agent.ps1 [--token TOKEN] [--url URL] [--install-dir DIR] [--no-service]"; exit 0 }
        default         { Die "Unknown argument: $($args[$i])" }
    }
}

if (-not $env:CONTROL_PLANE_URL) { Die 'CONTROL_PLANE_URL is required.' }
if (-not $env:TOKEN)             { Die 'TOKEN is required.' }

$env:CONTROL_PLANE_URL = $env:CONTROL_PLANE_URL.TrimEnd('/')

# ─── Detect architecture ────────────────────────────────────────────
switch ($env:PROCESSOR_ARCHITECTURE) {
    'AMD64' { $arch = 'amd64' }
    'x86'   { $arch = 'amd64' } # prefer amd64 under WoW64
    'ARM64' { $arch = 'arm64' }
    default { Die "Unsupported architecture: $env:PROCESSOR_ARCHITECTURE" }
}
$os = 'windows'
Write-Info "Platform: $os/$arch"

# ─── Must run elevated so we can write to Program Files + register the service
$identity  = [System.Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object System.Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Die 'This installer must be run as Administrator.'
}

$tmpDir = Join-Path $env:TEMP ("controlone-install-" + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $tmpDir -Force | Out-Null

try {
    $binaryUrl  = "$($env:CONTROL_PLANE_URL)/api/v1/agent/binary?os=$os&arch=$arch"
    $binaryPath = Join-Path $tmpDir 'controlone-agent.exe'

    Write-Info 'Downloading agent binary...'
    Invoke-WebRequest -Uri $binaryUrl -OutFile $binaryPath -UseBasicParsing
    if (-not (Test-Path $binaryPath) -or (Get-Item $binaryPath).Length -eq 0) {
        Die 'Download failed.'
    }
    Write-Ok 'Binary downloaded.'

    if (-not (Test-Path $env:INSTALL_DIR)) {
        New-Item -ItemType Directory -Path $env:INSTALL_DIR -Force | Out-Null
    }
    $installedBinary = Join-Path $env:INSTALL_DIR 'controlone-agent.exe'
    Copy-Item -Path $binaryPath -Destination $installedBinary -Force
    Write-Ok "Installed to $installedBinary."

    $enrollArgs = @('--join', $env:CONTROL_PLANE_URL, '--token', $env:TOKEN)
    if ($env:NO_SERVICE -ne 'true') { $enrollArgs += '--install-service' }

    Write-Info 'Enrolling agent...'
    & $installedBinary @enrollArgs
    if ($LASTEXITCODE -ne 0) { Die "Enrollment failed (exit $LASTEXITCODE)." }

    Write-Ok 'Control One agent installation complete!'
} finally {
    Remove-Item -Recurse -Force $tmpDir -ErrorAction SilentlyContinue
}
`

var (
	installScriptTmpl           = template.Must(template.New("install-script").Parse(installScriptTemplate))
	installScriptPowerShellTmpl = template.Must(template.New("install-script-powershell").Parse(installScriptPowerShellTemplate))
)

type installScriptData struct {
	CPURL string
	Token string
}

// installScriptVariant is the result of resolving the ?platform= query param
// to a concrete template + its HTTP metadata. Adding a new platform means
// adding an entry here (and a matching template const above).
type installScriptVariant struct {
	tmpl               *template.Template
	contentType        string
	contentDisposition string
}

// resolveInstallScriptVariant maps the `?platform=` query arg to the installer
// flavor to serve. Defaults to bash (linux/macOS) to preserve the
// pre-Windows-support one-liner. Unknown values also fall through to bash so
// older UI links don't regress to an error.
func resolveInstallScriptVariant(platform string) installScriptVariant {
	switch strings.ToLower(strings.TrimSpace(platform)) {
	case "windows", "win", "powershell", "ps1":
		return installScriptVariant{
			tmpl:               installScriptPowerShellTmpl,
			contentType:        "text/plain; charset=utf-8",
			contentDisposition: "attachment; filename=install-agent.ps1",
		}
	default:
		return installScriptVariant{
			tmpl:               installScriptTmpl,
			contentType:        "text/x-shellscript",
			contentDisposition: "attachment; filename=install-agent.sh",
		}
	}
}

func (s *Server) handleAgentInstallScript(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
		return
	}

	token := r.URL.Query().Get("token")

	// Derive the control plane URL from config or request.
	cpURL := s.deriveControlPlaneURL(r)

	data := installScriptData{
		CPURL: cpURL,
		Token: token,
	}

	variant := resolveInstallScriptVariant(r.URL.Query().Get("platform"))
	w.Header().Set("Content-Type", variant.contentType)
	w.Header().Set("Content-Disposition", variant.contentDisposition)

	if err := variant.tmpl.Execute(w, data); err != nil {
		s.logger.Error("render install script", zap.Error(err))
	}
}

func (s *Server) handleAgentBinary(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
		return
	}

	osParam := strings.TrimSpace(r.URL.Query().Get("os"))
	archParam := strings.TrimSpace(r.URL.Query().Get("arch"))

	if osParam == "" || archParam == "" {
		http.Error(w, "os and arch query parameters are required", http.StatusBadRequest)
		return
	}

	// Sanitize to prevent path traversal.
	osParam = filepath.Base(osParam)
	archParam = filepath.Base(archParam)

	binaryDir := s.cfg.Agent.BinaryDir
	if binaryDir == "" {
		http.Error(w, "agent binary directory not configured", http.StatusInternalServerError)
		return
	}

	filename := fmt.Sprintf("controlone-agent-%s-%s", osParam, archParam)
	binaryPath := filepath.Join(binaryDir, filename)

	info, err := os.Stat(binaryPath)
	if err != nil || info.IsDir() {
		http.Error(w, fmt.Sprintf("binary not found for %s/%s", osParam, archParam), http.StatusNotFound)
		return
	}

	w.Header().Set("Content-Type", "application/octet-stream")
	w.Header().Set("Content-Disposition", "attachment; filename=controlone-agent")

	http.ServeFile(w, r, binaryPath)
}

// deriveControlPlaneURL builds the control plane URL from config or the request host.
func (s *Server) deriveControlPlaneURL(r *http.Request) string {
	// If the HTTP config has an explicit address that looks like a full URL, use it.
	addr := strings.TrimSpace(s.cfg.HTTP.Address)
	if strings.HasPrefix(addr, "http://") || strings.HasPrefix(addr, "https://") {
		return strings.TrimRight(addr, "/")
	}

	// Derive from request.
	scheme := "https"
	if r.TLS == nil {
		scheme = "http"
	}
	host := r.Host
	if host == "" {
		host = r.URL.Host
	}
	if host == "" {
		host = "localhost"
	}

	return fmt.Sprintf("%s://%s", scheme, host)
}
