package server

import (
	"archive/tar"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"text/template"
	"time"

	"go.uber.org/zap"
)

// --- Offline bundle installer templates ---------------------------------

// installOfflineScriptTemplate is the air-gapped counterpart to
// installScriptTemplate: no network fetches, everything ships in the tarball.
// Signature verification runs through `controlone-agent verify-binary` with
// local paths so isolated networks never need to resolve the CP URL.
const installOfflineScriptTemplate = `#!/usr/bin/env bash
# Control One Agent Offline Installer
# Generated by the Control One control plane for air-gapped environments.
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fatal() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
CONFIG_DIR="${CONFIG_DIR:-/etc/control-one}"
NO_SERVICE="${NO_SERVICE:-false}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --install-dir) INSTALL_DIR="$2"; shift 2 ;;
        --config-dir)  CONFIG_DIR="$2"; shift 2 ;;
        --no-service)  NO_SERVICE="true"; shift ;;
        -h|--help)
            echo "Usage: $0 [--install-dir DIR] [--config-dir DIR] [--no-service]"
            exit 0 ;;
        *) fatal "Unknown argument: $1" ;;
    esac
done

SUDO=""
if [[ "$EUID" -ne 0 ]]; then
    command -v sudo >/dev/null 2>&1 && SUDO="sudo" || warn "Not root and no sudo."
fi

BINARY="${SCRIPT_DIR}/controlone-agent"
SIGNATURE="${SCRIPT_DIR}/controlone-agent.sig"
MANIFEST="${SCRIPT_DIR}/manifest.json"
CA_CERT="${SCRIPT_DIR}/ca.pem"
AGENT_CONFIG="${SCRIPT_DIR}/config.yaml"

[[ -f "$BINARY" ]]       || fatal "Bundled binary missing: $BINARY"
[[ -f "$MANIFEST" ]]     || fatal "Bundled manifest missing: $MANIFEST"
[[ -f "$AGENT_CONFIG" ]] || fatal "Bundled config missing: $AGENT_CONFIG"

chmod +x "$BINARY"

if command -v sha256sum >/dev/null 2>&1; then
    EXPECTED_SHA=$(sed -n 's/.*"sha256"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$MANIFEST")
    if [[ -n "$EXPECTED_SHA" ]]; then
        ACTUAL_SHA=$(sha256sum "$BINARY" | awk '{print $1}')
        if [[ "$EXPECTED_SHA" != "$ACTUAL_SHA" ]]; then
            fatal "Checksum mismatch: expected ${EXPECTED_SHA}, got ${ACTUAL_SHA}"
        fi
        ok "Checksum verified (sha256)."
    fi
fi

if [[ -f "$SIGNATURE" ]]; then
    if "$BINARY" verify-binary --binary "$BINARY" --signature-file "$SIGNATURE" >/dev/null 2>&1; then
        ok "Signature verified (ed25519, offline)."
    else
        warn "Signature verification failed or skipped."
    fi
fi

$SUDO mkdir -p "$INSTALL_DIR" "$CONFIG_DIR"
$SUDO install -m 0755 "$BINARY" "${INSTALL_DIR}/controlone-agent"
$SUDO install -m 0644 "$AGENT_CONFIG" "${CONFIG_DIR}/nodeagent.yaml"
if [[ -f "$CA_CERT" ]]; then
    $SUDO install -m 0644 "$CA_CERT" "${CONFIG_DIR}/ca.pem"
fi
ok "Installed to ${INSTALL_DIR}/controlone-agent."

ENROLL_ARGS=("--config" "${CONFIG_DIR}/nodeagent.yaml")
[[ "$NO_SERVICE" != "true" ]] && ENROLL_ARGS+=("--install-service")

info "Enrolling agent (offline)..."
$SUDO "${INSTALL_DIR}/controlone-agent" "${ENROLL_ARGS[@]}" || fatal "Enrollment failed."

ok "Control One agent offline installation complete."
`

// installOfflineScriptPowerShellTemplate mirrors the bash version for Windows
// air-gapped installs. Uses local paths exclusively and ships the CA cert into
// the configured ProgramData directory.
const installOfflineScriptPowerShellTemplate = `# Control One Agent Offline Installer (PowerShell)
$ErrorActionPreference = 'Stop'

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$InstallDir = if ($env:INSTALL_DIR) { $env:INSTALL_DIR } else { "$env:ProgramFiles\ControlOne" }
$ConfigDir  = if ($env:CONFIG_DIR)  { $env:CONFIG_DIR  } else { "$env:ProgramData\ControlOne" }

$Binary    = Join-Path $ScriptDir 'controlone-agent.exe'
$Signature = Join-Path $ScriptDir 'controlone-agent.sig'
$Manifest  = Join-Path $ScriptDir 'manifest.json'
$CACert    = Join-Path $ScriptDir 'ca.pem'
$Config    = Join-Path $ScriptDir 'config.yaml'

if (-not (Test-Path $Binary))   { throw "Bundled binary missing: $Binary" }
if (-not (Test-Path $Manifest)) { throw "Bundled manifest missing: $Manifest" }
if (-not (Test-Path $Config))   { throw "Bundled config missing: $Config" }

$ManifestData = Get-Content $Manifest -Raw | ConvertFrom-Json
if ($ManifestData.sha256) {
    $ActualSha = (Get-FileHash -Algorithm SHA256 $Binary).Hash.ToLower()
    if ($ActualSha -ne $ManifestData.sha256.ToLower()) {
        throw "Checksum mismatch: expected $($ManifestData.sha256), got $ActualSha"
    }
    Write-Host '[OK] Checksum verified (sha256).'
}

if (Test-Path $Signature) {
    try {
        & $Binary verify-binary --binary $Binary --signature-file $Signature | Out-Null
        Write-Host '[OK] Signature verified (ed25519, offline).'
    } catch {
        Write-Host '[WARN] Signature verification failed or skipped.'
    }
}

if (-not (Test-Path $InstallDir)) { New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null }
if (-not (Test-Path $ConfigDir))  { New-Item -ItemType Directory -Path $ConfigDir  -Force | Out-Null }

$InstalledBinary = Join-Path $InstallDir 'controlone-agent.exe'
$InstalledConfig = Join-Path $ConfigDir  'nodeagent.yaml'
Copy-Item -Force $Binary $InstalledBinary
Copy-Item -Force $Config $InstalledConfig
if (Test-Path $CACert) {
    Copy-Item -Force $CACert (Join-Path $ConfigDir 'ca.pem')
}
Write-Host "[OK] Installed to $InstalledBinary"

Write-Host '[INFO] Enrolling agent (offline)...'
& $InstalledBinary --config $InstalledConfig --install-service
if ($LASTEXITCODE -ne 0) { throw "Enrollment failed (exit $LASTEXITCODE)" }
Write-Host '[OK] Control One agent offline installation complete.'
`

// offlineConfigTemplate is the minimal `nodeagent.yaml` shipped in the bundle.
// The agent picks up the CP URL and bootstrap token from here so the installer
// never needs network access during enrollment.
const offlineConfigTemplate = `# Control One agent offline bootstrap config.
# Generated by the control plane bundle wizard.
api_url: "{{.CPURL}}"
bootstrap_token: "{{.Token}}"
tls:
  ca_cert_file: "{{.CAPath}}"
`

var (
	installOfflineScriptTmpl           = template.Must(template.New("install-offline").Parse(installOfflineScriptTemplate))
	installOfflineScriptPowerShellTmpl = template.Must(template.New("install-offline-ps").Parse(installOfflineScriptPowerShellTemplate))
	offlineConfigTmpl                  = template.Must(template.New("offline-config").Parse(offlineConfigTemplate))
)

// offlineConfigData feeds the embedded `config.yaml` so the bundled agent knows
// how to reach the control plane on first run.
type offlineConfigData struct {
	CPURL  string
	Token  string
	CAPath string
}

// bundleManifest is the envelope written to `manifest.json` inside the bundle.
// It reuses the SHA-256 and signature already computed for /agent/binary so the
// bundle endpoint is a pure recomposition of existing signed material.
type bundleManifest struct {
	OS                   string `json:"os"`
	Arch                 string `json:"arch"`
	SHA256               string `json:"sha256"`
	Signature            string `json:"signature,omitempty"`
	SizeBytes            int64  `json:"size_bytes"`
	PublicKeyFingerprint string `json:"public_key_fingerprint,omitempty"`
	GeneratedAt          string `json:"generated_at"`
	BundleFormat         string `json:"bundle_format"`
}

// handleAgentBundle serves a tarball with everything required to install the
// agent in an air-gapped environment: binary, signature, manifest, CA cert,
// offline install script, and a baked-in `config.yaml`. The caller supplies a
// valid enrollment token (`cot_xxx`) which is embedded in the config so the
// target node can auto-enroll on first run without leaving the isolated
// network to pull the token from the CP.
//
// The stream is built in-memory with `archive/tar` + `compress/gzip`. We stay
// bounded to O(binary size) memory because the binary is the only large file.
func (s *Server) handleAgentBundle(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
		return
	}

	if s.store == nil {
		http.Error(w, "storage unavailable", http.StatusServiceUnavailable)
		return
	}

	token := strings.TrimSpace(r.URL.Query().Get("token"))
	if token == "" {
		http.Error(w, "token query parameter is required", http.StatusBadRequest)
		return
	}
	if _, err := s.validateEnrollmentTokenForBundle(w, r, token); err != nil {
		// validateEnrollmentTokenForBundle writes the precise error to w;
		// we just short-circuit.
		return
	}

	osParam, archParam, ok := parseOSArch(w, r)
	if !ok {
		return
	}

	binaryPath, ok := s.resolveBinaryPath(w, osParam, archParam)
	if !ok {
		return
	}

	meta, err := s.binaryMetadataFor(binaryPath)
	if err != nil {
		s.logger.Error("compute bundle binary metadata", zap.Error(err), zap.String("path", binaryPath))
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}

	binaryBytes, err := os.ReadFile(binaryPath) // #nosec G304 — path derived from validated os/arch.
	if err != nil {
		s.logger.Error("read agent binary for bundle", zap.Error(err), zap.String("path", binaryPath))
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}

	// Belt-and-suspenders: reverify hash matches metadata. Guards against a
	// concurrent binary replacement between metadata compute and ReadFile.
	actual := sha256.Sum256(binaryBytes)
	if hex.EncodeToString(actual[:]) != meta.sha256 {
		s.logger.Error("bundle binary hash drift",
			zap.String("expected", meta.sha256),
			zap.String("actual", hex.EncodeToString(actual[:])),
		)
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}

	cpURL := s.deriveControlPlaneURL(r)

	caPEM := s.loadBundleCACert()
	caPath := "/etc/control-one/ca.pem"
	if isWindowsOS(osParam) {
		caPath = `C:\ProgramData\ControlOne\ca.pem`
	}

	configYAML, err := renderTemplate(offlineConfigTmpl, offlineConfigData{
		CPURL:  cpURL,
		Token:  token,
		CAPath: caPath,
	})
	if err != nil {
		s.logger.Error("render offline config", zap.Error(err))
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}

	installScript, installName, err := renderOfflineInstallScript(osParam)
	if err != nil {
		s.logger.Error("render offline install script", zap.Error(err))
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}

	mat := s.signingMaterial()
	manifest := bundleManifest{
		OS:           osParam,
		Arch:         archParam,
		SHA256:       meta.sha256,
		Signature:    meta.signature,
		SizeBytes:    meta.size,
		GeneratedAt:  time.Now().UTC().Format(time.RFC3339),
		BundleFormat: "controlone-bundle-v1",
	}
	if mat.havePublicKey {
		manifest.PublicKeyFingerprint = mat.fingerprint
	}
	manifestBytes, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		s.logger.Error("marshal bundle manifest", zap.Error(err))
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}

	binaryEntry := bundleBinaryName(osParam)

	entries := []bundleEntry{
		{name: binaryEntry, body: binaryBytes, mode: 0o755},
		{name: "manifest.json", body: manifestBytes, mode: 0o644},
		{name: "config.yaml", body: []byte(configYAML), mode: 0o644},
		{name: installName, body: []byte(installScript), mode: 0o755},
	}
	if len(caPEM) > 0 {
		entries = append(entries, bundleEntry{name: "ca.pem", body: caPEM, mode: 0o644})
	}
	if meta.signature != "" {
		// Embed the raw ed25519 signature bytes so offline verify can check without the manifest.
		entries = append(entries, bundleEntry{name: binaryEntry + ".sig", body: []byte(meta.signature), mode: 0o644})
	}

	filename := fmt.Sprintf("controlone-bundle-%s-%s.tar.gz", osParam, archParam)

	w.Header().Set("Content-Type", "application/gzip")
	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%s", filename))
	w.Header().Set("X-ControlOne-Checksum", "sha256-"+meta.sha256)
	if meta.signature != "" {
		w.Header().Set("X-ControlOne-Signature", "ed25519-"+meta.signature)
	}
	w.Header().Set("X-ControlOne-Bundle-Format", manifest.BundleFormat)

	if err := writeBundleTarball(w, entries); err != nil {
		s.logger.Warn("write bundle tarball", zap.Error(err))
	}
}

// bundleEntry captures one file written into the tarball.
type bundleEntry struct {
	name string
	body []byte
	mode int64
}

// writeBundleTarball streams tarball entries into w with gzip compression.
// The prefix directory is `controlone-bundle/` so `tar -xzf` lands everything
// under a single, well-known folder.
func writeBundleTarball(w io.Writer, entries []bundleEntry) error {
	gw := gzip.NewWriter(w)
	defer func() { _ = gw.Close() }()
	tw := tar.NewWriter(gw)
	defer func() { _ = tw.Close() }()

	now := time.Now().UTC()

	// Root directory entry first — tar readers that scan for dir mode take this as the package root.
	dirHeader := &tar.Header{
		Typeflag: tar.TypeDir,
		Name:     "controlone-bundle/",
		Mode:     0o755,
		ModTime:  now,
	}
	if err := tw.WriteHeader(dirHeader); err != nil {
		return fmt.Errorf("write bundle dir header: %w", err)
	}

	for _, entry := range entries {
		header := &tar.Header{
			Typeflag: tar.TypeReg,
			Name:     "controlone-bundle/" + entry.name,
			Mode:     entry.mode,
			Size:     int64(len(entry.body)),
			ModTime:  now,
		}
		if err := tw.WriteHeader(header); err != nil {
			return fmt.Errorf("write header for %s: %w", entry.name, err)
		}
		if _, err := tw.Write(entry.body); err != nil {
			return fmt.Errorf("write body for %s: %w", entry.name, err)
		}
	}

	if err := tw.Close(); err != nil {
		return fmt.Errorf("close tar writer: %w", err)
	}
	if err := gw.Close(); err != nil {
		return fmt.Errorf("close gzip writer: %w", err)
	}
	return nil
}

// validateEnrollmentTokenForBundle hashes + looks up the provided token and
// enforces the same revoked/expired checks used by the enrollment endpoint.
// On failure the helper writes the precise HTTP status to w and returns a
// non-nil error so callers can short-circuit without re-writing a response.
func (s *Server) validateEnrollmentTokenForBundle(w http.ResponseWriter, r *http.Request, token string) (string, error) {
	h := sha256.Sum256([]byte(strings.TrimSpace(token)))
	tokenHash := hex.EncodeToString(h[:])

	record, err := s.store.GetEnrollmentTokenByHash(r.Context(), tokenHash)
	if err != nil {
		s.logger.Error("lookup enrollment token for bundle", zap.Error(err))
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return "", err
	}
	if record == nil {
		http.Error(w, "invalid enrollment token", http.StatusUnauthorized)
		return "", fmt.Errorf("invalid enrollment token")
	}
	if record.RevokedAt.Valid {
		http.Error(w, "enrollment token has been revoked", http.StatusUnauthorized)
		return "", fmt.Errorf("token revoked")
	}
	if time.Now().After(record.ExpiresAt) {
		http.Error(w, "enrollment token has expired", http.StatusUnauthorized)
		return "", fmt.Errorf("token expired")
	}
	return tokenHash, nil
}

// renderOfflineInstallScript chooses between the bash and powershell offline
// templates based on the requested OS.
func renderOfflineInstallScript(osName string) (string, string, error) {
	if isWindowsOS(osName) {
		body, err := renderTemplate(installOfflineScriptPowerShellTmpl, nil)
		if err != nil {
			return "", "", err
		}
		return body, "install-offline.ps1", nil
	}
	body, err := renderTemplate(installOfflineScriptTmpl, nil)
	if err != nil {
		return "", "", err
	}
	return body, "install-offline.sh", nil
}

// renderTemplate executes a template into a string, returning the rendered body
// or a formatted error.
func renderTemplate(tmpl *template.Template, data any) (string, error) {
	var sb strings.Builder
	if err := tmpl.Execute(&sb, data); err != nil {
		return "", fmt.Errorf("render %s: %w", tmpl.Name(), err)
	}
	return sb.String(), nil
}

// bundleBinaryName returns the filename used for the agent binary inside the
// tarball. Windows callers get the `.exe` suffix so the script can launch the
// correct target.
func bundleBinaryName(osName string) string {
	if isWindowsOS(osName) {
		return "controlone-agent.exe"
	}
	return "controlone-agent"
}

// isWindowsOS lets the dispatcher pick the right script template + file name.
func isWindowsOS(osName string) bool {
	return strings.EqualFold(osName, "windows")
}

// loadBundleCACert reads the configured enrollment CA certificate so the bundle
// can include it. If the CA isn't configured (dev mode) we return nil and the
// installer will still work, it just won't pin mTLS.
func (s *Server) loadBundleCACert() []byte {
	caPath := strings.TrimSpace(s.cfg.Enrollment.CACertFile)
	if caPath == "" {
		return nil
	}
	data, err := os.ReadFile(caPath) // #nosec G304 — admin-controlled path.
	if err != nil {
		s.logger.Warn("read enrollment CA cert for bundle", zap.String("path", caPath), zap.Error(err))
		return nil
	}
	return data
}
