package server

import (
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/google/uuid"
	"sync"
	"text/template"

	"go.uber.org/zap"
)

// --- Bash installer template ---------------------------------------------

const installScriptTemplate = `#!/usr/bin/env bash
# Control One Agent Installer
# Generated by the Control One control plane.
set -euo pipefail

# ─── Colors ─────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fatal() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ─── Baked-in values from control plane ─────────────────────────────
CONTROL_PLANE_URL="${CONTROL_PLANE_URL:-{{.CPURL}}}"
TOKEN="${TOKEN:-{{.Token}}}"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
NO_SERVICE="${NO_SERVICE:-false}"
# Base64-encoded PEM of a custom root CA to trust. When present the installer
# writes it to /usr/local/share/ca-certificates/controlone.crt (or the distro
# equivalent) and passes --cacert to curl so fetching the binary + manifest
# still works under an internal PKI.
CA_CERT_B64="${CA_CERT_B64:-{{.CACert}}}"
CA_CERT_FILE=""

# ─── Parse arguments ────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --token)       TOKEN="$2"; shift 2 ;;
        --url)         CONTROL_PLANE_URL="$2"; shift 2 ;;
        --install-dir) INSTALL_DIR="$2"; shift 2 ;;
        --ca-cert)     CA_CERT_B64="$2"; shift 2 ;;
        --no-service)  NO_SERVICE="true"; shift ;;
        -h|--help)
            echo "Usage: $0 [--token TOKEN] [--url URL] [--install-dir DIR] [--ca-cert B64] [--no-service]"
            exit 0 ;;
        *) fatal "Unknown argument: $1" ;;
    esac
done

[[ -z "$CONTROL_PLANE_URL" ]] && fatal "CONTROL_PLANE_URL is required."
[[ -z "$TOKEN" ]] && fatal "TOKEN is required."

CONTROL_PLANE_URL="${CONTROL_PLANE_URL%/}"

# ─── Detect platform + distro ──────────────────────────────────────
detect_os() {
    local os; os="$(uname -s | tr '[:upper:]' '[:lower:]')"
    case "$os" in
        linux)  echo "linux" ;;
        darwin) echo "darwin" ;;
        *)      fatal "Unsupported OS: $os" ;;
    esac
}

detect_arch() {
    local arch; arch="$(uname -m)"
    case "$arch" in
        x86_64|amd64)  echo "amd64" ;;
        aarch64|arm64) echo "arm64" ;;
        *)             fatal "Unsupported arch: $arch" ;;
    esac
}

# detect_distro echoes a normalized distro family when /etc/os-release is
# available: debian|rhel|suse|alpine|arch. macOS + unknown Linux fall through
# to "generic". The value is only used for cert trust + init-system hints.
detect_distro() {
    if [[ "$(uname -s)" != "Linux" ]]; then
        echo "generic"
        return
    fi
    if [[ -r /etc/os-release ]]; then
        # shellcheck disable=SC1091
        . /etc/os-release
        local id="${ID:-}"
        local like="${ID_LIKE:-}"
        case "$id $like" in
            *ubuntu*|*debian*)             echo "debian"; return ;;
            *rhel*|*centos*|*rocky*|*almalinux*|*fedora*|*ol*) echo "rhel"; return ;;
            *opensuse*|*suse*|*sles*)      echo "suse"; return ;;
            *alpine*)                      echo "alpine"; return ;;
            *arch*)                        echo "arch"; return ;;
        esac
    fi
    echo "generic"
}

# detect_init echoes the active init system: systemd|openrc|sysv|unknown.
detect_init() {
    if [[ -d /run/systemd/system ]] || command -v systemctl >/dev/null 2>&1; then
        echo "systemd"; return
    fi
    if [[ -x /sbin/openrc-run ]] || [[ -d /etc/init.d && -x /sbin/rc-service ]]; then
        echo "openrc"; return
    fi
    if [[ -d /etc/init.d ]]; then
        echo "sysv"; return
    fi
    echo "unknown"
}

OS="$(detect_os)"
ARCH="$(detect_arch)"
DISTRO="$(detect_distro)"
INIT_SYSTEM="$(detect_init)"
info "Platform: ${OS}/${ARCH} (distro=${DISTRO}, init=${INIT_SYSTEM})"

command -v curl >/dev/null 2>&1 || fatal "curl is required."

# ─── Install custom root CA if supplied ────────────────────────────
install_custom_ca() {
    [[ -z "$CA_CERT_B64" ]] && return
    local decoded="${TMP_DIR}/controlone-ca.pem"
    if ! printf '%s' "$CA_CERT_B64" | base64 -d > "$decoded" 2>/dev/null; then
        fatal "Failed to decode --ca-cert (expect base64-encoded PEM)."
    fi
    CA_CERT_FILE="$decoded"
    case "$OS" in
        linux)
            case "$DISTRO" in
                debian)
                    $SUDO cp "$decoded" /usr/local/share/ca-certificates/controlone.crt || true
                    $SUDO update-ca-certificates >/dev/null 2>&1 || warn "update-ca-certificates failed; curl will still use --cacert."
                    ;;
                rhel|suse)
                    $SUDO cp "$decoded" /etc/pki/ca-trust/source/anchors/controlone.crt 2>/dev/null \
                        || $SUDO cp "$decoded" /etc/ca-certificates/trust-source/anchors/controlone.crt 2>/dev/null \
                        || true
                    $SUDO update-ca-trust extract >/dev/null 2>&1 || true
                    ;;
                alpine)
                    $SUDO cp "$decoded" /usr/local/share/ca-certificates/controlone.crt 2>/dev/null || true
                    $SUDO update-ca-certificates >/dev/null 2>&1 || true
                    ;;
                *)
                    warn "Unknown distro for CA install; curl will still use --cacert."
                    ;;
            esac
            ;;
        darwin)
            $SUDO security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$decoded" >/dev/null 2>&1 \
                || warn "security add-trusted-cert failed; curl will still use --cacert."
            ;;
    esac
    ok "Custom root CA installed."
}

SUDO=""
if [[ "$EUID" -ne 0 ]]; then
    command -v sudo >/dev/null 2>&1 && SUDO="sudo" || warn "Not root and no sudo."
fi

TMP_DIR="$(mktemp -d)"
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

install_custom_ca

# ─── Pre-flight: heal broken state before installing ────────────────
# Idempotent — safe to run on both fresh and existing hosts.
repair_agent_state() {
    # Stop any running agent so the binary can be atomically replaced and cert
    # files are not held open by a live process during re-enrollment.
    if command -v systemctl >/dev/null 2>&1; then
        if systemctl is-active --quiet controlone-agent 2>/dev/null; then
            info "Stopping existing agent service..."
            $SUDO systemctl stop controlone-agent 2>/dev/null || true
        fi
    elif command -v rc-service >/dev/null 2>&1; then
        $SUDO rc-service controlone-agent stop 2>/dev/null || true
    fi

    # The agent's default plugin_dir is /opt/control-one/nodeagent/plugins.
    # If a previous install left the agent binary at /opt/control-one/nodeagent
    # (a file), os.MkdirAll panics with "not a directory" on every startup.
    # Detect any path component that is a regular file where a directory is needed.
    local -a conflict_paths=(
        "/opt/control-one/nodeagent"
    )
    for p in "${conflict_paths[@]}"; do
        if [[ -e "$p" ]] && [[ ! -d "$p" ]]; then
            warn "Path conflict: ${p} is a file but the agent needs it as a directory. Relocating..."
            $SUDO mv "$p" "${p}.bak.$(date +%s)" 2>/dev/null || $SUDO rm -f "$p" || true
            ok "Cleared conflicting path: ${p}"
        fi
    done

    # Remove 0-byte cert files. They were written during a failed enrollment
    # (e.g. server/agent JSON tag mismatch). os.WriteFile overwrites them on
    # re-enrollment but tls.LoadX509KeyPair will fatal if they are still empty
    # at next boot before re-enrollment completes.
    local cert_dir="/var/lib/control-one/nodeagent/certs"
    if [[ -d "$cert_dir" ]]; then
        local wiped=0
        for f in "${cert_dir}"/*.crt "${cert_dir}"/*.key; do
            [[ -e "$f" ]] || continue
            if [[ ! -s "$f" ]]; then
                $SUDO rm -f "$f"
                wiped=$((wiped + 1))
            fi
        done
        [[ $wiped -gt 0 ]] && warn "Removed ${wiped} empty cert file(s); fresh certs will be issued on enrollment."
    fi
}

repair_agent_state

CURL_OPTS=(-fsSL)
if [[ -n "$CA_CERT_FILE" ]]; then
    CURL_OPTS+=(--cacert "$CA_CERT_FILE")
fi

BINARY_URL="${CONTROL_PLANE_URL}/api/v1/agent/binary?os=${OS}&arch=${ARCH}"
MANIFEST_URL="${CONTROL_PLANE_URL}/api/v1/agent/binary/manifest?os=${OS}&arch=${ARCH}"
BINARY_PATH="${TMP_DIR}/controlone-agent"
MANIFEST_PATH="${TMP_DIR}/manifest.json"

info "Fetching binary manifest..."
HTTP_CODE=$(curl "${CURL_OPTS[@]}" -w "%{http_code}" -o "$MANIFEST_PATH" "$MANIFEST_URL" 2>/dev/null || true)
if [[ "${HTTP_CODE}" != "200" ]] || [[ ! -s "$MANIFEST_PATH" ]]; then
    warn "Manifest unavailable (HTTP ${HTTP_CODE:-???}); proceeding without integrity check."
    MANIFEST_PATH=""
fi

info "Downloading agent binary..."
HTTP_CODE=$(curl "${CURL_OPTS[@]}" -w "%{http_code}" -o "$BINARY_PATH" "$BINARY_URL" 2>/dev/null) || true

[[ ! -f "$BINARY_PATH" ]] || [[ ! -s "$BINARY_PATH" ]] && fatal "Download failed (HTTP ${HTTP_CODE:-???})."
[[ "${HTTP_CODE}" != "200" ]] && fatal "Unexpected HTTP ${HTTP_CODE}."

ok "Binary downloaded."

if [[ -n "${MANIFEST_PATH}" ]] && command -v sha256sum >/dev/null 2>&1; then
    EXPECTED_SHA=$(sed -n 's/.*"sha256"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$MANIFEST_PATH")
    if [[ -n "$EXPECTED_SHA" ]]; then
        ACTUAL_SHA=$(sha256sum "$BINARY_PATH" | awk '{print $1}')
        if [[ "$EXPECTED_SHA" != "$ACTUAL_SHA" ]]; then
            fatal "Checksum mismatch: expected ${EXPECTED_SHA}, got ${ACTUAL_SHA}"
        fi
        ok "Checksum verified (sha256)."
    fi

    EXPECTED_SIG=$(sed -n 's/.*"signature"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$MANIFEST_PATH")
    if [[ -n "$EXPECTED_SIG" ]]; then
        # Best-effort ed25519 verify via the agent itself once installed to tmp.
        chmod +x "$BINARY_PATH"
        if "$BINARY_PATH" verify-binary --binary "$BINARY_PATH" --signature "$EXPECTED_SIG" --public-key-url "${CONTROL_PLANE_URL}/api/v1/agent/public-key" >/dev/null 2>&1; then
            ok "Signature verified (ed25519)."
        else
            warn "Signature verification skipped or unavailable."
        fi
    fi
fi

$SUDO mkdir -p "$INSTALL_DIR"
$SUDO install -m 0755 "$BINARY_PATH" "${INSTALL_DIR}/controlone-agent"
ok "Installed to ${INSTALL_DIR}/controlone-agent."

ENROLL_ARGS=("--join" "$CONTROL_PLANE_URL" "--token" "$TOKEN")
[[ -n "$CA_CERT_FILE" ]] && ENROLL_ARGS+=("--ca-cert" "$CA_CERT_FILE")
[[ "$NO_SERVICE" != "true" ]] && ENROLL_ARGS+=("--install-service")
[[ -n "$INIT_SYSTEM" && "$INIT_SYSTEM" != "systemd" ]] && ENROLL_ARGS+=("--init-system" "$INIT_SYSTEM")

info "Enrolling agent..."
$SUDO "${INSTALL_DIR}/controlone-agent" "${ENROLL_ARGS[@]}" || fatal "Enrollment failed."

ok "Control One agent installation complete!"
`

// --- Bash uninstall template ---------------------------------------------

const uninstallScriptTemplate = `#!/usr/bin/env bash
# Control One Agent Uninstaller
# Generated by the Control One control plane.
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fatal() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"

SUDO=""
if [[ "$EUID" -ne 0 ]]; then
    command -v sudo >/dev/null 2>&1 && SUDO="sudo" || warn "Not root and no sudo."
fi

AGENT="${INSTALL_DIR}/controlone-agent"
if [[ ! -x "$AGENT" ]]; then
    fatal "Agent binary not found at $AGENT"
fi

info "Running agent uninstall..."
$SUDO "$AGENT" uninstall || warn "Agent reported an error during uninstall; continuing."

$SUDO rm -f "$AGENT"
ok "Control One agent uninstalled."
`

// --- PowerShell templates -----------------------------------------------

const installScriptPowerShellTemplate = `# Control One Agent Installer (PowerShell)
# Generated by the Control One control plane.
$ErrorActionPreference = 'Stop'

$ControlPlaneURL = if ($env:CONTROL_PLANE_URL) { $env:CONTROL_PLANE_URL } else { '{{.CPURL}}' }
$Token           = if ($env:TOKEN)             { $env:TOKEN }             else { '{{.Token}}' }
$InstallDir      = if ($env:INSTALL_DIR)       { $env:INSTALL_DIR }       else { "$env:ProgramFiles\ControlOne" }

if ([string]::IsNullOrWhiteSpace($ControlPlaneURL)) { throw 'CONTROL_PLANE_URL is required.' }
if ([string]::IsNullOrWhiteSpace($Token))           { throw 'TOKEN is required.' }

$ControlPlaneURL = $ControlPlaneURL.TrimEnd('/')

# Detect architecture
$Arch = switch ($env:PROCESSOR_ARCHITECTURE) {
    'AMD64' { 'amd64' }
    'ARM64' { 'arm64' }
    default { throw "Unsupported arch: $($env:PROCESSOR_ARCHITECTURE)" }
}
Write-Host "[INFO] Platform: windows/$Arch"

$TmpDir      = Join-Path $env:TEMP ("controlone-" + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $TmpDir | Out-Null
$BinaryPath  = Join-Path $TmpDir 'controlone-agent.exe'
$ManifestPath = Join-Path $TmpDir 'manifest.json'

try {
    $BinaryURL   = "$ControlPlaneURL/api/v1/agent/binary?os=windows&arch=$Arch"
    $ManifestURL = "$ControlPlaneURL/api/v1/agent/binary/manifest?os=windows&arch=$Arch"

    Write-Host '[INFO] Fetching binary manifest...'
    try {
        Invoke-WebRequest -UseBasicParsing -Uri $ManifestURL -OutFile $ManifestPath
    } catch {
        Write-Host '[WARN] Manifest unavailable; proceeding without integrity check.'
        $ManifestPath = $null
    }

    Write-Host '[INFO] Downloading agent binary...'
    Invoke-WebRequest -UseBasicParsing -Uri $BinaryURL -OutFile $BinaryPath

    if ($ManifestPath -and (Test-Path $ManifestPath)) {
        $Manifest = Get-Content $ManifestPath -Raw | ConvertFrom-Json
        if ($Manifest.sha256) {
            $ActualSha = (Get-FileHash -Algorithm SHA256 $BinaryPath).Hash.ToLower()
            if ($ActualSha -ne $Manifest.sha256.ToLower()) {
                throw "Checksum mismatch: expected $($Manifest.sha256), got $ActualSha"
            }
            Write-Host '[OK] Checksum verified (sha256).'
        }
        if ($Manifest.signature) {
            try {
                & $BinaryPath verify-binary --binary $BinaryPath --signature $Manifest.signature --public-key-url "$ControlPlaneURL/api/v1/agent/public-key" | Out-Null
                Write-Host '[OK] Signature verified (ed25519).'
            } catch {
                Write-Host '[WARN] Signature verification skipped or unavailable.'
            }
        }
    }

    if (-not (Test-Path $InstallDir)) {
        New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
    }
    $InstalledPath = Join-Path $InstallDir 'controlone-agent.exe'
    Copy-Item -Force $BinaryPath $InstalledPath
    Write-Host "[OK] Installed to $InstalledPath"

    Write-Host '[INFO] Enrolling agent...'
    & $InstalledPath --join $ControlPlaneURL --token $Token --install-service
    if ($LASTEXITCODE -ne 0) { throw "Enrollment failed (exit $LASTEXITCODE)" }

    Write-Host '[OK] Control One agent installation complete!'
} finally {
    if (Test-Path $TmpDir) { Remove-Item -Recurse -Force $TmpDir }
}
`

const uninstallScriptPowerShellTemplate = `# Control One Agent Uninstaller (PowerShell)
$ErrorActionPreference = 'Stop'

$InstallDir = if ($env:INSTALL_DIR) { $env:INSTALL_DIR } else { "$env:ProgramFiles\ControlOne" }
$Agent = Join-Path $InstallDir 'controlone-agent.exe'

if (-not (Test-Path $Agent)) {
    throw "Agent binary not found at $Agent"
}

Write-Host '[INFO] Running agent uninstall...'
try {
    & $Agent uninstall
} catch {
    Write-Host "[WARN] Agent reported an error during uninstall; continuing: $_"
}

Remove-Item -Force $Agent -ErrorAction SilentlyContinue
Write-Host '[OK] Control One agent uninstalled.'
`

var (
	installScriptTmpl             = template.Must(template.New("install-script").Parse(installScriptTemplate))
	uninstallScriptTmpl           = template.Must(template.New("uninstall-script").Parse(uninstallScriptTemplate))
	installScriptPowerShellTmpl   = template.Must(template.New("install-script-ps").Parse(installScriptPowerShellTemplate))
	uninstallScriptPowerShellTmpl = template.Must(template.New("uninstall-script-ps").Parse(uninstallScriptPowerShellTemplate))
)

type installScriptData struct {
	CPURL  string
	Token  string
	CACert string // base64-encoded PEM of a custom root CA to trust; empty for system trust store
}

// sanitizeBase64 strips whitespace and rejects values that are not valid
// base64 so template expansion cannot smuggle arbitrary shell metadata through
// the `ca_cert` query parameter.
func sanitizeBase64(raw string) string {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return ""
	}
	// Allow both standard and URL-safe alphabets + optional padding.
	if _, err := base64.StdEncoding.DecodeString(trimmed); err != nil {
		if _, err := base64.RawStdEncoding.DecodeString(trimmed); err != nil {
			if _, err := base64.URLEncoding.DecodeString(trimmed); err != nil {
				return ""
			}
		}
	}
	return trimmed
}

// binaryManifest is the JSON payload returned by /api/v1/agent/binary/manifest.
//
// PR 4a fields (release_seq, rollout_pct, target_version) are advisory: the
// agent reads them to gate self-update by stable rollout bucket and reject
// downgrades. When agent_rollout_state has no row for the calling tenant —
// the default — release_seq is 0 and rollout_pct is 0, which means the
// agent treats every update as "outside the wave" and skips. Operators
// must explicitly set rollout_pct > 0 to begin a rollout.
type binaryManifest struct {
	OS                   string `json:"os"`
	Arch                 string `json:"arch"`
	SHA256               string `json:"sha256"`
	Signature            string `json:"signature,omitempty"`
	SizeBytes            int64  `json:"size_bytes"`
	PublicKeyFingerprint string `json:"public_key_fingerprint,omitempty"`
	ReleaseSeq           int    `json:"release_seq,omitempty"`
	RolloutPct           int    `json:"rollout_pct,omitempty"`
	TargetVersion        string `json:"target_version,omitempty"`
	Paused               bool   `json:"paused,omitempty"`
}

// binaryMetadata caches hash/signature/size for a single binary file.
type binaryMetadata struct {
	sha256    string
	signature string
	size      int64
}

// agentSigningMaterial holds the active ed25519 signing key + public-key material.
type agentSigningMaterial struct {
	privateKey      ed25519.PrivateKey
	publicKey       ed25519.PublicKey
	publicKeyPEM    []byte
	fingerprint     string
	haveSigningKey  bool
	havePublicKey   bool
	manifestCache   map[string]binaryMetadata
	manifestCacheMu sync.Mutex
}

// resolveSigningMaterial loads the signing key + public key from Agent config.
// Returns a best-effort result: if either is missing, the server still serves
// binaries but logs a WARN and omits signatures (dev-friendly fallback).
func (s *Server) resolveSigningMaterial() *agentSigningMaterial {
	mat := &agentSigningMaterial{
		manifestCache: make(map[string]binaryMetadata),
	}

	if keyPath := strings.TrimSpace(s.cfg.Agent.SigningKeyPath); keyPath != "" {
		priv, err := loadEd25519PrivateKey(keyPath)
		if err != nil {
			s.logger.Warn("agent signing key unavailable; binaries will be served unsigned",
				zap.String("path", keyPath), zap.Error(err))
		} else {
			mat.privateKey = priv
			mat.haveSigningKey = true
		}
	} else {
		s.logger.Warn("agent signing key not configured; binaries will be served unsigned")
	}

	if pubPath := strings.TrimSpace(s.cfg.Agent.SigningPublicKeyPath); pubPath != "" {
		pemBytes, err := os.ReadFile(pubPath)
		if err != nil {
			s.logger.Warn("agent signing public key unavailable", zap.String("path", pubPath), zap.Error(err))
		} else {
			pub, fp, err := parseEd25519PublicKeyPEM(pemBytes)
			if err != nil {
				s.logger.Warn("agent signing public key parse failed", zap.String("path", pubPath), zap.Error(err))
			} else {
				mat.publicKey = pub
				mat.publicKeyPEM = pemBytes
				mat.fingerprint = fp
				mat.havePublicKey = true
			}
		}
	} else if mat.haveSigningKey {
		// Derive the public key from the private key (but no PEM to serve).
		if p, ok := mat.privateKey.Public().(ed25519.PublicKey); ok {
			mat.publicKey = p
			mat.fingerprint = ed25519Fingerprint(p)
			mat.havePublicKey = true
		}
	}

	return mat
}

// signingMaterial returns the server's signing material, computing it on first use.
func (s *Server) signingMaterial() *agentSigningMaterial {
	s.agentSigningOnce.Do(func() {
		s.agentSigning = s.resolveSigningMaterial()
	})
	return s.agentSigning
}

func (s *Server) binaryMetadataFor(path string) (binaryMetadata, error) {
	mat := s.signingMaterial()
	key := path

	mat.manifestCacheMu.Lock()
	defer mat.manifestCacheMu.Unlock()
	if meta, ok := mat.manifestCache[key]; ok {
		return meta, nil
	}

	f, err := os.Open(path) // #nosec G304 — path derived from validated os/arch + configured BinaryDir
	if err != nil {
		return binaryMetadata{}, err
	}
	defer func() { _ = f.Close() }()

	info, err := f.Stat()
	if err != nil {
		return binaryMetadata{}, err
	}

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return binaryMetadata{}, err
	}
	sum := h.Sum(nil)

	meta := binaryMetadata{
		sha256: hex.EncodeToString(sum),
		size:   info.Size(),
	}
	if mat.haveSigningKey {
		sig := ed25519.Sign(mat.privateKey, sum)
		meta.signature = base64.StdEncoding.EncodeToString(sig)
	}
	mat.manifestCache[key] = meta
	return meta, nil
}

// --- HTTP handlers ------------------------------------------------------

func (s *Server) handleAgentInstallScript(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
		return
	}

	token := r.URL.Query().Get("token")
	platform := strings.ToLower(strings.TrimSpace(r.URL.Query().Get("platform")))
	mode := strings.ToLower(strings.TrimSpace(r.URL.Query().Get("mode")))

	// Derive the control plane URL from config or request.
	cpURL := s.deriveControlPlaneURL(r)

	data := installScriptData{
		CPURL:  cpURL,
		Token:  token,
		CACert: sanitizeBase64(r.URL.Query().Get("ca_cert")),
	}

	var (
		tmpl        *template.Template
		contentType string
		filename    string
	)

	switch platform {
	case "windows", "ps", "powershell":
		contentType = "text/plain; charset=utf-8"
		if mode == "uninstall" {
			tmpl = uninstallScriptPowerShellTmpl
			filename = "uninstall-agent.ps1"
		} else {
			tmpl = installScriptPowerShellTmpl
			filename = "install-agent.ps1"
		}
	default:
		contentType = "text/x-shellscript"
		if mode == "uninstall" {
			tmpl = uninstallScriptTmpl
			filename = "uninstall-agent.sh"
		} else {
			tmpl = installScriptTmpl
			filename = "install-agent.sh"
		}
	}

	w.Header().Set("Content-Type", contentType)
	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%s", filename))

	if err := tmpl.Execute(w, data); err != nil {
		s.logger.Error("render install script", zap.Error(err))
	}
}

func (s *Server) handleAgentBinary(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
		return
	}

	osParam, archParam, ok := parseOSArch(w, r)
	if !ok {
		return
	}

	binaryPath, ok := s.resolveBinaryPath(w, osParam, archParam)
	if !ok {
		return
	}

	meta, err := s.binaryMetadataFor(binaryPath)
	if err != nil {
		s.logger.Error("compute binary metadata", zap.Error(err), zap.String("path", binaryPath))
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/octet-stream")
	w.Header().Set("Content-Disposition", "attachment; filename=controlone-agent")
	w.Header().Set("X-ControlOne-Checksum", "sha256-"+meta.sha256)
	if meta.signature != "" {
		w.Header().Set("X-ControlOne-Signature", "ed25519-"+meta.signature)
	}

	http.ServeFile(w, r, binaryPath)
}

func (s *Server) handleAgentBinaryManifest(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
		return
	}

	osParam, archParam, ok := parseOSArch(w, r)
	if !ok {
		return
	}

	binaryPath, ok := s.resolveBinaryPath(w, osParam, archParam)
	if !ok {
		return
	}

	meta, err := s.binaryMetadataFor(binaryPath)
	if err != nil {
		s.logger.Error("compute binary metadata for manifest", zap.Error(err), zap.String("path", binaryPath))
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}

	mat := s.signingMaterial()
	manifest := binaryManifest{
		OS:        osParam,
		Arch:      archParam,
		SHA256:    meta.sha256,
		Signature: meta.signature,
		SizeBytes: meta.size,
	}
	if mat.havePublicKey {
		manifest.PublicKeyFingerprint = mat.fingerprint
	}

	// PR 4a: agent passes ?node_id=<id> so the server can resolve tenant
	// and stamp release_seq + rollout_pct. Missing/invalid node_id leaves
	// the rollout fields zero, which the agent treats as "outside the
	// wave" and skips — fail-closed behaviour.
	if nidStr := strings.TrimSpace(r.URL.Query().Get("node_id")); nidStr != "" {
		if nid, err := uuid.Parse(nidStr); err == nil {
			if node, err := s.store.GetNode(r.Context(), nid); err == nil && node != nil {
				if state, err := s.store.GetAgentRolloutState(r.Context(), node.TenantID); err == nil && state != nil {
					manifest.ReleaseSeq = state.TargetReleaseSeq
					manifest.RolloutPct = state.RolloutPct
					manifest.TargetVersion = state.TargetVersion
					manifest.Paused = state.Paused
				}
			}
		}
	}

	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(manifest); err != nil {
		s.logger.Warn("encode binary manifest", zap.Error(err))
	}
}

func (s *Server) handleAgentPublicKey(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
		return
	}

	mat := s.signingMaterial()
	if !mat.havePublicKey {
		http.Error(w, "agent signing public key not configured", http.StatusNotFound)
		return
	}

	if len(mat.publicKeyPEM) > 0 {
		w.Header().Set("Content-Type", "application/x-pem-file")
		if _, err := w.Write(mat.publicKeyPEM); err != nil {
			s.logger.Warn("write public key response", zap.Error(err))
		}
		return
	}

	// Fall back to encoding the raw key as PEM.
	der, err := x509.MarshalPKIXPublicKey(mat.publicKey)
	if err != nil {
		s.logger.Error("marshal agent public key", zap.Error(err))
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}
	pemBlock := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der})
	w.Header().Set("Content-Type", "application/x-pem-file")
	if _, err := w.Write(pemBlock); err != nil {
		s.logger.Warn("write public key response", zap.Error(err))
	}
}

// --- helpers ------------------------------------------------------------

// parseOSArch extracts sanitized os/arch query params, writing a 400 on error.
func parseOSArch(w http.ResponseWriter, r *http.Request) (string, string, bool) {
	osParam := strings.TrimSpace(r.URL.Query().Get("os"))
	archParam := strings.TrimSpace(r.URL.Query().Get("arch"))

	if osParam == "" || archParam == "" {
		http.Error(w, "os and arch query parameters are required", http.StatusBadRequest)
		return "", "", false
	}

	// Sanitize to prevent path traversal.
	return filepath.Base(osParam), filepath.Base(archParam), true
}

// resolveBinaryPath locates a binary under the configured BinaryDir.
func (s *Server) resolveBinaryPath(w http.ResponseWriter, osParam, archParam string) (string, bool) {
	binaryDir := s.cfg.Agent.BinaryDir
	if binaryDir == "" {
		http.Error(w, "agent binary directory not configured", http.StatusInternalServerError)
		return "", false
	}

	filename := fmt.Sprintf("controlone-agent-%s-%s", osParam, archParam)
	binaryPath := filepath.Join(binaryDir, filename)

	info, err := os.Stat(binaryPath)
	if err != nil || info.IsDir() {
		http.Error(w, fmt.Sprintf("binary not found for %s/%s", osParam, archParam), http.StatusNotFound)
		return "", false
	}
	return binaryPath, true
}

// deriveControlPlaneURL builds the control plane URL from config or the request host.
func (s *Server) deriveControlPlaneURL(r *http.Request) string {
	// If the HTTP config has an explicit address that looks like a full URL, use it.
	addr := strings.TrimSpace(s.cfg.HTTP.Address)
	if strings.HasPrefix(addr, "http://") || strings.HasPrefix(addr, "https://") {
		return strings.TrimRight(addr, "/")
	}

	// Prefer X-Forwarded-Proto set by the reverse proxy (nginx).
	// Fall back to TLS detection, then plain http.
	scheme := "https"
	if fwd := strings.TrimSpace(r.Header.Get("X-Forwarded-Proto")); fwd != "" {
		scheme = fwd
	} else if r.TLS == nil {
		scheme = "http"
	}

	host := r.Host
	if host == "" {
		host = r.URL.Host
	}
	if host == "" {
		host = "localhost"
	}

	return fmt.Sprintf("%s://%s", scheme, host)
}

// --- ed25519 key helpers ------------------------------------------------

func loadEd25519PrivateKey(path string) (ed25519.PrivateKey, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read ed25519 private key: %w", err)
	}

	block, _ := pem.Decode(data)
	if block != nil {
		key, perr := parseEd25519PrivateKeyBytes(block.Bytes)
		if perr != nil {
			return nil, perr
		}
		return key, nil
	}

	// Also accept raw base64-encoded PKCS#8 or seed.
	trimmed := bytes.TrimSpace(data)
	decoded, err := base64.StdEncoding.DecodeString(string(trimmed))
	if err == nil {
		if key, perr := parseEd25519PrivateKeyBytes(decoded); perr == nil {
			return key, nil
		}
	}

	return nil, errors.New("unsupported ed25519 private key encoding")
}

func parseEd25519PrivateKeyBytes(der []byte) (ed25519.PrivateKey, error) {
	// Try PKCS#8 first (ed25519 is standard here).
	if key, err := x509.ParsePKCS8PrivateKey(der); err == nil {
		if pk, ok := key.(ed25519.PrivateKey); ok {
			return pk, nil
		}
		return nil, errors.New("private key is not ed25519")
	}
	// Fallback: raw 64-byte private key (ed25519 standard).
	if len(der) == ed25519.PrivateKeySize {
		out := make(ed25519.PrivateKey, ed25519.PrivateKeySize)
		copy(out, der)
		return out, nil
	}
	// Or a 32-byte seed.
	if len(der) == ed25519.SeedSize {
		return ed25519.NewKeyFromSeed(der), nil
	}
	return nil, errors.New("unable to parse ed25519 private key")
}

func parseEd25519PublicKeyPEM(data []byte) (ed25519.PublicKey, string, error) {
	block, _ := pem.Decode(data)
	if block == nil {
		// Try raw base64.
		trimmed := bytes.TrimSpace(data)
		decoded, err := base64.StdEncoding.DecodeString(string(trimmed))
		if err != nil {
			return nil, "", errors.New("unsupported public key encoding")
		}
		if len(decoded) == ed25519.PublicKeySize {
			pk := ed25519.PublicKey(decoded)
			return pk, ed25519Fingerprint(pk), nil
		}
		pub, err := x509.ParsePKIXPublicKey(decoded)
		if err != nil {
			return nil, "", fmt.Errorf("parse ed25519 public key: %w", err)
		}
		pk, ok := pub.(ed25519.PublicKey)
		if !ok {
			return nil, "", errors.New("public key is not ed25519")
		}
		return pk, ed25519Fingerprint(pk), nil
	}

	pub, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, "", fmt.Errorf("parse ed25519 public key: %w", err)
	}
	pk, ok := pub.(ed25519.PublicKey)
	if !ok {
		return nil, "", errors.New("public key is not ed25519")
	}
	return pk, ed25519Fingerprint(pk), nil
}

func ed25519Fingerprint(pk ed25519.PublicKey) string {
	if len(pk) == 0 {
		return ""
	}
	sum := sha256.Sum256(pk)
	return "sha256:" + hex.EncodeToString(sum[:])
}
