package server

import (
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"go.uber.org/zap"
)

const installScriptTemplate = `#!/usr/bin/env bash
# Control One Agent Installer
# Generated by the Control One control plane.
set -euo pipefail

# ─── Colors ─────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fatal() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ─── Baked-in values from control plane ─────────────────────────────
CONTROL_PLANE_URL="${CONTROL_PLANE_URL:-{{.CPURL}}}"
TOKEN="${TOKEN:-{{.Token}}}"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
NO_SERVICE="${NO_SERVICE:-false}"

# ─── Parse arguments ────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --token)      TOKEN="$2"; shift 2 ;;
        --url)        CONTROL_PLANE_URL="$2"; shift 2 ;;
        --install-dir) INSTALL_DIR="$2"; shift 2 ;;
        --no-service) NO_SERVICE="true"; shift ;;
        -h|--help)
            echo "Usage: $0 [--token TOKEN] [--url URL] [--install-dir DIR] [--no-service]"
            exit 0 ;;
        *) fatal "Unknown argument: $1" ;;
    esac
done

[[ -z "$CONTROL_PLANE_URL" ]] && fatal "CONTROL_PLANE_URL is required."
[[ -z "$TOKEN" ]] && fatal "TOKEN is required."

CONTROL_PLANE_URL="${CONTROL_PLANE_URL%/}"

# ─── Detect platform ────────────────────────────────────────────────
detect_os() {
    local os; os="$(uname -s | tr '[:upper:]' '[:lower:]')"
    case "$os" in
        linux)  echo "linux" ;;
        darwin) echo "darwin" ;;
        *)      fatal "Unsupported OS: $os" ;;
    esac
}

detect_arch() {
    local arch; arch="$(uname -m)"
    case "$arch" in
        x86_64|amd64)  echo "amd64" ;;
        aarch64|arm64) echo "arm64" ;;
        *)             fatal "Unsupported arch: $arch" ;;
    esac
}

OS="$(detect_os)"
ARCH="$(detect_arch)"
info "Platform: ${OS}/${ARCH}"

command -v curl >/dev/null 2>&1 || fatal "curl is required."

SUDO=""
if [[ "$EUID" -ne 0 ]]; then
    command -v sudo >/dev/null 2>&1 && SUDO="sudo" || warn "Not root and no sudo."
fi

TMP_DIR="$(mktemp -d)"
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

BINARY_URL="${CONTROL_PLANE_URL}/api/v1/agent/binary?os=${OS}&arch=${ARCH}"
BINARY_PATH="${TMP_DIR}/controlone-agent"

info "Downloading agent binary..."
HTTP_CODE=$(curl -fsSL -w "%%{http_code}" -o "$BINARY_PATH" "$BINARY_URL" 2>/dev/null) || true

[[ ! -f "$BINARY_PATH" ]] || [[ ! -s "$BINARY_PATH" ]] && fatal "Download failed (HTTP ${HTTP_CODE:-???})."
[[ "${HTTP_CODE}" != "200" ]] && fatal "Unexpected HTTP ${HTTP_CODE}."

ok "Binary downloaded."

$SUDO mkdir -p "$INSTALL_DIR"
$SUDO install -m 0755 "$BINARY_PATH" "${INSTALL_DIR}/controlone-agent"
ok "Installed to ${INSTALL_DIR}/controlone-agent."

ENROLL_ARGS=("--join" "$CONTROL_PLANE_URL" "--token" "$TOKEN")
[[ "$NO_SERVICE" != "true" ]] && ENROLL_ARGS+=("--install-service")

info "Enrolling agent..."
$SUDO "${INSTALL_DIR}/controlone-agent" "${ENROLL_ARGS[@]}" || fatal "Enrollment failed."

ok "Control One agent installation complete!"
`

var installScriptTmpl = template.Must(template.New("install-script").Parse(installScriptTemplate))

type installScriptData struct {
	CPURL string
	Token string
}

func (s *Server) handleAgentInstallScript(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
		return
	}

	token := r.URL.Query().Get("token")

	// Derive the control plane URL from config or request.
	cpURL := s.deriveControlPlaneURL(r)

	data := installScriptData{
		CPURL: cpURL,
		Token: token,
	}

	w.Header().Set("Content-Type", "text/x-shellscript")
	w.Header().Set("Content-Disposition", "attachment; filename=install-agent.sh")

	if err := installScriptTmpl.Execute(w, data); err != nil {
		s.logger.Error("render install script", zap.Error(err))
	}
}

func (s *Server) handleAgentBinary(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
		return
	}

	osParam := strings.TrimSpace(r.URL.Query().Get("os"))
	archParam := strings.TrimSpace(r.URL.Query().Get("arch"))

	if osParam == "" || archParam == "" {
		http.Error(w, "os and arch query parameters are required", http.StatusBadRequest)
		return
	}

	// Sanitize to prevent path traversal.
	osParam = filepath.Base(osParam)
	archParam = filepath.Base(archParam)

	binaryDir := s.cfg.Agent.BinaryDir
	if binaryDir == "" {
		http.Error(w, "agent binary directory not configured", http.StatusInternalServerError)
		return
	}

	filename := fmt.Sprintf("controlone-agent-%s-%s", osParam, archParam)
	binaryPath := filepath.Join(binaryDir, filename)

	info, err := os.Stat(binaryPath)
	if err != nil || info.IsDir() {
		http.Error(w, fmt.Sprintf("binary not found for %s/%s", osParam, archParam), http.StatusNotFound)
		return
	}

	w.Header().Set("Content-Type", "application/octet-stream")
	w.Header().Set("Content-Disposition", "attachment; filename=controlone-agent")

	http.ServeFile(w, r, binaryPath)
}

// deriveControlPlaneURL builds the control plane URL from config or the request host.
func (s *Server) deriveControlPlaneURL(r *http.Request) string {
	// If the HTTP config has an explicit address that looks like a full URL, use it.
	addr := strings.TrimSpace(s.cfg.HTTP.Address)
	if strings.HasPrefix(addr, "http://") || strings.HasPrefix(addr, "https://") {
		return strings.TrimRight(addr, "/")
	}

	// Derive from request.
	scheme := "https"
	if r.TLS == nil {
		scheme = "http"
	}
	host := r.Host
	if host == "" {
		host = r.URL.Host
	}
	if host == "" {
		host = "localhost"
	}

	return fmt.Sprintf("%s://%s", scheme, host)
}
