package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"time"

	"github.com/CloudSpaceLab/control_one/internal/util"
)

type enrollRequest struct {
	Token       string `json:"token"`
	Hostname    string `json:"hostname"`
	OS          string `json:"os"`
	Arch        string `json:"arch"`
	PublicIP    string `json:"public_ip"`
	Fingerprint string `json:"fingerprint"`
}

type enrollResponse struct {
	NodeID   string `json:"node_id"`
	TenantID string `json:"tenant_id"`
	TLS      struct {
		ClientCert string `json:"client_cert"`
		ClientKey  string `json:"client_key"`
		CACert     string `json:"ca_cert"`
	} `json:"tls"`
	Config enrollConfig `json:"config"`
}

type enrollConfig struct {
	APIURL       string            `json:"api_url"`
	Intervals    map[string]int64  `json:"intervals"`
	Compliance   map[string]any    `json:"compliance"`
	Labels       map[string]string `json:"labels"`
	Capabilities []string          `json:"capabilities"`
}

func runJoin(joinURL, token, nodeName, configDir, dataDir string, installService, startAgent bool) error {
	// 1. Gather system info
	sysInfo := util.GatherSystemInfo()
	hostname := sysInfo.Hostname
	if nodeName != "" {
		hostname = nodeName
	}

	// 2. POST to /api/v1/enroll
	reqBody := enrollRequest{
		Token:       token,
		Hostname:    hostname,
		OS:          sysInfo.OS,
		Arch:        sysInfo.Arch,
		PublicIP:    sysInfo.PublicIP,
		Fingerprint: sysInfo.Fingerprint,
	}

	bodyBytes, err := json.Marshal(reqBody)
	if err != nil {
		return fmt.Errorf("marshal enroll request: %w", err)
	}

	resp, err := http.Post(joinURL+"/api/v1/enroll", "application/json", bytes.NewReader(bodyBytes))
	if err != nil {
		return fmt.Errorf("enroll request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		// Read error body
		var errBody struct {
			Error string `json:"error"`
		}
		json.NewDecoder(resp.Body).Decode(&errBody)
		if errBody.Error != "" {
			return fmt.Errorf("enrollment rejected: %s", errBody.Error)
		}
		return fmt.Errorf("enrollment rejected: HTTP %d", resp.StatusCode)
	}

	var enrollResp enrollResponse
	if err := json.NewDecoder(resp.Body).Decode(&enrollResp); err != nil {
		return fmt.Errorf("decode enroll response: %w", err)
	}

	// 3. Create directories
	certDir := filepath.Join(dataDir, "certs")
	policyDir := filepath.Join(dataDir, "policies")
	logDir := "/var/log/control-one/nodeagent"

	for _, dir := range []string{certDir, policyDir, logDir, configDir, filepath.Dir(filepath.Join(dataDir, "state.json"))} {
		if err := os.MkdirAll(dir, 0750); err != nil {
			return fmt.Errorf("create dir %s: %w", dir, err)
		}
	}

	// 4. Write TLS certs
	if err := os.WriteFile(filepath.Join(certDir, "client.crt"), []byte(enrollResp.TLS.ClientCert), 0640); err != nil {
		return fmt.Errorf("write client cert: %w", err)
	}
	if err := os.WriteFile(filepath.Join(certDir, "client.key"), []byte(enrollResp.TLS.ClientKey), 0600); err != nil {
		return fmt.Errorf("write client key: %w", err)
	}
	if err := os.WriteFile(filepath.Join(certDir, "ca.crt"), []byte(enrollResp.TLS.CACert), 0640); err != nil {
		return fmt.Errorf("write CA cert: %w", err)
	}

	// 5. Generate nodeagent.yaml config
	// Build intervals from response (with sensible defaults)
	heartbeat := getInterval(enrollResp.Config.Intervals, "heartbeat", 60)
	policySync := getInterval(enrollResp.Config.Intervals, "policy_sync", 600)
	scan := getInterval(enrollResp.Config.Intervals, "scan", 300)
	telemetry := getInterval(enrollResp.Config.Intervals, "telemetry", 60)

	configContent := fmt.Sprintf(`# Auto-generated by controlone-agent join
# Control Plane: %s
# Node ID: %s
# Enrolled: %s

api_url: "%s"
node_name: "%s"
state_file: "%s"
policy_dir: "%s"
log_dir: "%s"

tls:
  cert_file: "%s"
  key_file: "%s"
  ca_cert_file: "%s"

intervals:
  heartbeat: %ds
  policy_sync: %ds
  scan: %ds
  telemetry: %ds

scanner:
  enabled: true
  use_real_scan: true

wizard:
  enabled: true
  auto_generate_certificates: false
  run_access_sync: true
  run_secrets_sync: true
  run_compliance: true
  emit_summary: true
`,
		joinURL, enrollResp.NodeID, time.Now().UTC().Format(time.RFC3339),
		joinURL, hostname,
		filepath.Join(dataDir, "state.json"),
		policyDir, logDir,
		filepath.Join(certDir, "client.crt"),
		filepath.Join(certDir, "client.key"),
		filepath.Join(certDir, "ca.crt"),
		heartbeat, policySync, scan, telemetry,
	)

	configPath := filepath.Join(configDir, "nodeagent.yaml")
	if err := os.WriteFile(configPath, []byte(configContent), 0640); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	// 6. Write state file
	stateContent, _ := json.MarshalIndent(map[string]any{
		"node_id":       enrollResp.NodeID,
		"registered_at": time.Now().UTC(),
	}, "", "  ")
	if err := os.WriteFile(filepath.Join(dataDir, "state.json"), stateContent, 0600); err != nil {
		return fmt.Errorf("write state: %w", err)
	}

	// 7. Print summary
	fmt.Println("")
	fmt.Println("  Enrolled successfully")
	fmt.Printf("  Node ID:  %s\n", enrollResp.NodeID)
	fmt.Printf("  Tenant:   %s\n", enrollResp.TenantID)
	fmt.Printf("  Config:   %s\n", configPath)
	fmt.Printf("  Certs:    %s\n", certDir)
	fmt.Println("")

	// 8. Install systemd service if requested
	if installService {
		if err := installSystemdService(configPath); err != nil {
			return fmt.Errorf("install service: %w", err)
		}
		fmt.Println("  Service:  controlone-agent.service (enabled + started)")
	} else if !startAgent {
		fmt.Printf("  Run: controlone-agent --config %s\n", configPath)
	}
	fmt.Println("")

	return nil
}

func getInterval(intervals map[string]int64, key string, defaultVal int64) int64 {
	if v, ok := intervals[key]; ok && v > 0 {
		return v
	}
	return defaultVal
}

func installSystemdService(configPath string) error {
	if runtime.GOOS != "linux" {
		return fmt.Errorf("systemd service install only supported on Linux")
	}

	// Find the agent binary path
	binaryPath, err := os.Executable()
	if err != nil {
		binaryPath = "/usr/local/bin/controlone-agent"
	}

	unit := fmt.Sprintf(`[Unit]
Description=Control One Node Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=%s --config %s
Restart=on-failure
RestartSec=10
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
`, binaryPath, configPath)

	servicePath := "/etc/systemd/system/controlone-agent.service"
	if err := os.WriteFile(servicePath, []byte(unit), 0644); err != nil {
		return fmt.Errorf("write service file: %w", err)
	}

	// Reload and enable
	if err := exec.Command("systemctl", "daemon-reload").Run(); err != nil {
		return fmt.Errorf("systemctl daemon-reload: %w", err)
	}
	if err := exec.Command("systemctl", "enable", "--now", "controlone-agent").Run(); err != nil {
		return fmt.Errorf("systemctl enable: %w", err)
	}

	return nil
}
