package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/CloudSpaceLab/control_one/internal/util"
)

type enrollRequest struct {
	Token              string `json:"token"`
	Hostname           string `json:"hostname"`
	OS                 string `json:"os"`
	Arch               string `json:"arch"`
	PublicIP           string `json:"public_ip"`
	Fingerprint        string `json:"fingerprint"`
	MachineID          string `json:"machine_id,omitempty"`
	CompliancePolicyID string `json:"compliance_policy_id,omitempty"`
}

type enrollResponse struct {
	NodeID    string `json:"node_id"`
	TenantID  string `json:"tenant_id"`
	NodeToken string `json:"node_token,omitempty"` // bearer token for agent auth
	TLS       struct {
		ClientCert string `json:"client_cert"`
		ClientKey  string `json:"client_key"`
		CACert     string `json:"ca_cert"`
	} `json:"tls"`
	Config enrollConfig `json:"config"`
	Policy struct {
		PublicKeyPEM string `json:"public_key_pem"`
	} `json:"policy"`
}

type enrollConfig struct {
	APIURL       string            `json:"api_url"`
	Intervals    map[string]int64  `json:"intervals"`
	Compliance   map[string]any    `json:"compliance"`
	Labels       map[string]string `json:"labels"`
	Capabilities []string          `json:"capabilities"`
}

func runJoin(joinURL, token, nodeName, configDir, dataDir, compliancePolicyID string, installService, startAgent bool) error {
	// 1. Gather system info
	sysInfo := util.GatherSystemInfo()
	hostname := sysInfo.Hostname
	if nodeName != "" {
		hostname = nodeName
	}

	// 2. POST to /api/v1/enroll
	machineID, _ := util.ReadMachineID()
	reqBody := enrollRequest{
		Token:              token,
		Hostname:           hostname,
		OS:                 sysInfo.OS,
		Arch:               sysInfo.Arch,
		PublicIP:           sysInfo.PublicIP,
		Fingerprint:        sysInfo.Fingerprint,
		MachineID:          machineID,
		CompliancePolicyID: strings.TrimSpace(compliancePolicyID),
	}

	bodyBytes, err := json.Marshal(reqBody)
	if err != nil {
		return fmt.Errorf("marshal enroll request: %w", err)
	}

	resp, err := http.Post(joinURL+"/api/v1/enroll", "application/json", bytes.NewReader(bodyBytes))
	if err != nil {
		return fmt.Errorf("enroll request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		// Read error body
		var errBody struct {
			Error string `json:"error"`
		}
		_ = json.NewDecoder(resp.Body).Decode(&errBody)
		if errBody.Error != "" {
			return fmt.Errorf("enrollment rejected: %s", errBody.Error)
		}
		return fmt.Errorf("enrollment rejected: HTTP %d", resp.StatusCode)
	}

	var enrollResp enrollResponse
	if err := json.NewDecoder(resp.Body).Decode(&enrollResp); err != nil {
		return fmt.Errorf("decode enroll response: %w", err)
	}

	// 3. Create directories
	certDir := filepath.Join(dataDir, "certs")
	policyDir := filepath.Join(dataDir, "policies")
	keyDir := filepath.Join(dataDir, "keys")
	logDir := filepath.Join(dataDir, "logs")
	if installService && runtime.GOOS != "windows" {
		logDir = "/var/log/control-one/nodeagent"
	}

	for _, dir := range []string{certDir, policyDir, keyDir, logDir, configDir, filepath.Dir(filepath.Join(dataDir, "state.json"))} {
		if err := os.MkdirAll(dir, 0750); err != nil {
			return fmt.Errorf("create dir %s: %w", dir, err)
		}
	}

	// 4. Write TLS certs
	if err := os.WriteFile(filepath.Join(certDir, "client.crt"), []byte(enrollResp.TLS.ClientCert), 0640); err != nil {
		return fmt.Errorf("write client cert: %w", err)
	}
	if err := os.WriteFile(filepath.Join(certDir, "client.key"), []byte(enrollResp.TLS.ClientKey), 0600); err != nil {
		return fmt.Errorf("write client key: %w", err)
	}
	if err := os.WriteFile(filepath.Join(certDir, "ca.crt"), []byte(enrollResp.TLS.CACert), 0640); err != nil {
		return fmt.Errorf("write CA cert: %w", err)
	}

	// 4b. Write policy public key (when the server is configured with one).
	// The empty case is normal — the server hasn't enabled policy signing yet
	// — and we still emit a `policy.public_key_file: ""` line below so the
	// agent's config-default doesn't take over and point at a path no one
	// created.
	policyKeyPath := ""
	if pem := strings.TrimSpace(enrollResp.Policy.PublicKeyPEM); pem != "" {
		policyKeyPath = filepath.Join(keyDir, "policy_pub.pem")
		if err := os.WriteFile(policyKeyPath, []byte(pem+"\n"), 0644); err != nil {
			return fmt.Errorf("write policy public key: %w", err)
		}
	}

	// 5. Generate nodeagent.yaml config
	// Build intervals from response (with sensible defaults)
	heartbeat := getInterval(enrollResp.Config.Intervals, "heartbeat", 60)
	policySync := getInterval(enrollResp.Config.Intervals, "policy_sync", 600)
	scan := getInterval(enrollResp.Config.Intervals, "scan", 300)
	telemetry := getInterval(enrollResp.Config.Intervals, "telemetry", 60)

	configContent := fmt.Sprintf(`# Auto-generated by controlone-agent join
# Control Plane: %s
# Node ID: %s
# Enrolled: %s

api_url: "%s"
node_name: "%s"
node_token: "%s"
state_file: "%s"
policy_dir: "%s"
log_dir: "%s"

tls:
  cert_file: "%s"
  key_file: "%s"
  ca_cert_file: "%s"

policy:
  public_key_file: "%s"

network_policy:
  enforcement_mode: dry_run

intervals:
  heartbeat: %ds
  policy_sync: %ds
  scan: %ds
  telemetry: %ds

agent_runtime:
  profile: auto

telemetry_prefs:
  collect_logs: false
  auto_discover_log_sources: true
  log_sources: []

app_dependencies:
  enabled: true
  scan_roots: []
  include_dev_dependencies: false
  scan_interval: 6h
  max_depth: 8
  max_manifests: 512
  max_file_bytes: 1048576

scanner:
  enabled: true
  use_real_scan: true

wizard:
  enabled: true
  auto_generate_certificates: false
  run_access_sync: true
  run_secrets_sync: true
  run_compliance: true
  emit_summary: true
`,
		joinURL, enrollResp.NodeID, time.Now().UTC().Format(time.RFC3339),
		joinURL, hostname, enrollResp.NodeToken,
		// All on-disk paths run through filepath.ToSlash because the YAML
		// template uses double-quoted strings, where a Windows-style
		// "C:\Users\..." would be parsed as escape sequences (\U expects
		// 8 hex digits and panics the YAML loader). Forward slashes are
		// accepted as path separators by Go's os/filepath on Windows.
		filepath.ToSlash(filepath.Join(dataDir, "state.json")),
		filepath.ToSlash(policyDir), filepath.ToSlash(logDir),
		filepath.ToSlash(filepath.Join(certDir, "client.crt")),
		filepath.ToSlash(filepath.Join(certDir, "client.key")),
		filepath.ToSlash(filepath.Join(certDir, "ca.crt")),
		filepath.ToSlash(policyKeyPath),
		heartbeat, policySync, scan, telemetry,
	)

	configPath := filepath.Join(configDir, "nodeagent.yaml")
	if err := os.WriteFile(configPath, []byte(configContent), 0640); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	// 6. Write state file
	stateContent, _ := json.MarshalIndent(map[string]any{
		"node_id":       enrollResp.NodeID,
		"tenant_id":     enrollResp.TenantID,
		"registered_at": time.Now().UTC(),
	}, "", "  ")
	if err := os.WriteFile(filepath.Join(dataDir, "state.json"), stateContent, 0600); err != nil {
		return fmt.Errorf("write state: %w", err)
	}

	// 7. Print summary
	fmt.Println("")
	fmt.Println("  Enrolled successfully")
	fmt.Printf("  Node ID:  %s\n", enrollResp.NodeID)
	fmt.Printf("  Tenant:   %s\n", enrollResp.TenantID)
	fmt.Printf("  Config:   %s\n", configPath)
	fmt.Printf("  Certs:    %s\n", certDir)
	fmt.Println("")

	if warnings := runPrimaryHardening(); len(warnings) == 0 {
		fmt.Println("  Hardening: primary baseline applied")
	} else {
		fmt.Println("  Hardening: primary baseline completed with warnings")
		for _, warning := range warnings {
			fmt.Printf("    - %s\n", warning)
		}
	}
	fmt.Println("")

	// 9. Install OS-managed service if requested. Platform dispatch is
	//    handled by the build-tagged service_*.go files — see service_linux.go
	//    for systemd, service_darwin.go for launchd, service_windows.go for
	//    the Windows Service Control Manager.
	if installService {
		if err := installServiceFn(configPath); err != nil {
			return fmt.Errorf("install service: %w", err)
		}
		fmt.Println("  Service:  controlone-agent (enabled + started)")
	} else if !startAgent {
		fmt.Printf("  Run: controlone-agent --config %s\n", configPath)
	}
	fmt.Println("")

	return nil
}

func getInterval(intervals map[string]int64, key string, defaultVal int64) int64 {
	if v, ok := intervals[key]; ok && v > 0 {
		return v
	}
	return defaultVal
}

// installServiceFn indirects through a package variable so tests can swap in
// a stub without touching the OS service manager. The real implementation is
// provided per-platform in service_{linux,darwin,windows}.go (with a fallback
// in service.go).
var installServiceFn = installService
