-- Maps framework controls (SOC2, HIPAA, PCI-DSS, ISO27001, GDPR) to the CIS
-- baseline policy slugs seeded in 0077. Used by control-coverage roll-ups in
-- the audit report generator and the Compliance Posture tab.
--
-- policy_rule_id matches the policy.name (slug) seeded in 0077, which is also
-- the value compliance_results.rule_id carries when results are written.

CREATE TABLE IF NOT EXISTS framework_control_mappings (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    framework       TEXT NOT NULL,
    control_id      TEXT NOT NULL,
    policy_rule_id  TEXT NOT NULL,
    rationale       TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (framework, control_id, policy_rule_id)
);

CREATE INDEX IF NOT EXISTS idx_fcm_framework_control ON framework_control_mappings(framework, control_id);
CREATE INDEX IF NOT EXISTS idx_fcm_policy            ON framework_control_mappings(policy_rule_id);

INSERT INTO framework_control_mappings (framework, control_id, policy_rule_id, rationale) VALUES
    -- SOC2 TSC 2017
    ('SOC2', 'CC6.1',  'fail2ban_enabled',     'Brute-force lockout supports logical access controls'),
    ('SOC2', 'CC6.1',  'ssh_password_auth',    'Key-based SSH satisfies authentication policy'),
    ('SOC2', 'CC6.1',  'mac_enabled',          'Mandatory access control enforces logical access policy'),
    ('SOC2', 'CC6.1',  'password_min_length',  'Password length is a logical access control'),
    ('SOC2', 'CC6.1',  'password_max_days',    'Password rotation is a logical access control'),
    ('SOC2', 'CC6.1',  'account_lockout',      'Account lockout limits unauthorized access'),
    ('SOC2', 'CC6.1',  'selinux_enforcing',    'SELinux enforcing mode is a logical access control'),
    ('SOC2', 'CC6.3',  'ssh_root_login',       'Privileged-account access restricted'),
    ('SOC2', 'CC6.3',  'shadow_perms',         'Credential file protected from unauthorized access'),
    ('SOC2', 'CC6.3',  'passwd_perms',         'Identity store protected from tampering'),
    ('SOC2', 'CC6.3',  'umask_secure',         'Default file permissions limit lateral access'),
    ('SOC2', 'CC6.6',  'firewall_enabled',     'Boundary protection on host'),
    ('SOC2', 'CC6.6',  'ssh_protocol_2',       'Encrypted-channel authentication'),
    ('SOC2', 'CC6.6',  'telnet_closed',        'Cleartext-protocol surface eliminated'),
    ('SOC2', 'CC6.6',  'ftp_closed',           'Cleartext-protocol surface eliminated'),
    ('SOC2', 'CC6.6',  'rsh_closed',           'Cleartext-protocol surface eliminated'),
    ('SOC2', 'CC6.6',  'nis_closed',           'Legacy directory service disabled'),
    ('SOC2', 'CC6.6',  'mysql_public',         'Datastore not exposed to public network'),
    ('SOC2', 'CC6.6',  'postgres_public',      'Datastore not exposed to public network'),
    ('SOC2', 'CC6.6',  'redis_public',         'Datastore not exposed to public network'),
    ('SOC2', 'CC6.6',  'nfs_disabled',         'File-sharing surface eliminated'),
    ('SOC2', 'CC7.1',  'auto_updates',         'Vulnerability management via patching'),
    ('SOC2', 'CC7.2',  'auditd_enabled',       'Continuous monitoring of system activity'),
    ('SOC2', 'CC7.2',  'time_sync',            'Reliable timestamps required for monitoring'),

    -- HIPAA Security Rule
    ('HIPAA', '164.308(a)(5)',     'fail2ban_enabled',    'Security awareness — protection against malicious software'),
    ('HIPAA', '164.308(a)(5)',     'auto_updates',        'Security awareness — protection against malicious software'),
    ('HIPAA', '164.308(a)(5)',     'account_lockout',     'Security awareness — log-in monitoring'),
    ('HIPAA', '164.308(a)(5)(ii)(D)', 'password_min_length', 'Password management addressable spec'),
    ('HIPAA', '164.308(a)(5)(ii)(D)', 'password_max_days',   'Password management addressable spec'),
    ('HIPAA', '164.312(a)(1)',     'ssh_root_login',      'Access control — unique user identification'),
    ('HIPAA', '164.312(a)(1)',     'mac_enabled',         'Access control — emergency access procedure baseline'),
    ('HIPAA', '164.312(a)(1)',     'shadow_perms',        'Access control — credential protection'),
    ('HIPAA', '164.312(a)(1)',     'passwd_perms',        'Access control — identity-store protection'),
    ('HIPAA', '164.312(a)(1)',     'umask_secure',        'Access control — default file permissions'),
    ('HIPAA', '164.312(a)(1)',     'mysql_public',        'Access control — protected health info datastore'),
    ('HIPAA', '164.312(a)(1)',     'postgres_public',     'Access control — protected health info datastore'),
    ('HIPAA', '164.312(a)(1)',     'redis_public',        'Access control — protected health info datastore'),
    ('HIPAA', '164.312(a)(1)',     'nis_closed',          'Access control — legacy directory disabled'),
    ('HIPAA', '164.312(a)(1)',     'firewall_enabled',    'Access control — boundary protection'),
    ('HIPAA', '164.312(a)(1)',     'selinux_enforcing',   'Access control — mandatory access enforcement'),
    ('HIPAA', '164.312(b)',        'auditd_enabled',      'Audit controls'),
    ('HIPAA', '164.312(b)',        'time_sync',           'Audit controls — reliable timestamps'),
    ('HIPAA', '164.312(d)',        'ssh_password_auth',   'Person-or-entity authentication'),
    ('HIPAA', '164.312(e)(1)',     'ssh_protocol_2',      'Transmission security'),
    ('HIPAA', '164.312(e)(1)',     'telnet_closed',       'Transmission security — cleartext eliminated'),
    ('HIPAA', '164.312(e)(1)',     'ftp_closed',          'Transmission security — cleartext eliminated'),
    ('HIPAA', '164.312(e)(1)',     'rsh_closed',          'Transmission security — cleartext eliminated'),
    ('HIPAA', '164.312(e)(1)',     'nfs_disabled',        'Transmission security — uncontrolled share disabled'),

    -- PCI-DSS v4.0
    ('PCI-DSS', '1.1',     'firewall_enabled',     'Network security controls in place'),
    ('PCI-DSS', '4.2',     'ssh_protocol_2',       'Encrypt cardholder data in transit'),
    ('PCI-DSS', '4.2',     'nfs_disabled',         'Untrusted-network exposure eliminated'),
    ('PCI-DSS', '4.2.1',   'telnet_closed',        'Strong cryptography on transmissions'),
    ('PCI-DSS', '4.2.1',   'ftp_closed',           'Strong cryptography on transmissions'),
    ('PCI-DSS', '4.2.1',   'rsh_closed',           'Strong cryptography on transmissions'),
    ('PCI-DSS', '6.3.3',   'fail2ban_enabled',     'Vulnerabilities are protected from exploitation'),
    ('PCI-DSS', '6.3.3',   'auto_updates',         'Patches applied promptly'),
    ('PCI-DSS', '6.5',     'mysql_public',         'CDE network segmentation'),
    ('PCI-DSS', '6.5',     'postgres_public',      'CDE network segmentation'),
    ('PCI-DSS', '6.5',     'redis_public',         'CDE network segmentation'),
    ('PCI-DSS', '6.5',     'nis_closed',           'Insecure protocols disabled'),
    ('PCI-DSS', '6.7',     'mac_enabled',          'Secure system configuration'),
    ('PCI-DSS', '6.7',     'selinux_enforcing',    'Secure system configuration'),
    ('PCI-DSS', '7.1',     'ssh_root_login',       'Need-to-know based access restricted'),
    ('PCI-DSS', '7.1',     'shadow_perms',         'Credential access restricted'),
    ('PCI-DSS', '7.1',     'passwd_perms',         'System file access restricted'),
    ('PCI-DSS', '7.1',     'umask_secure',         'Default permissions follow least-privilege'),
    ('PCI-DSS', '8.3.4',   'account_lockout',      'Repeated authentication failures locked out'),
    ('PCI-DSS', '8.3.6',   'ssh_password_auth',    'Strong authentication'),
    ('PCI-DSS', '8.3.6',   'password_min_length',  'Authentication factor strength'),
    ('PCI-DSS', '8.3.9',   'password_max_days',    'Password change frequency'),
    ('PCI-DSS', '10.2',    'auditd_enabled',       'Audit logs generated'),
    ('PCI-DSS', '10.6',    'time_sync',            'Time synchronization for audit logs'),

    -- ISO/IEC 27001:2022 Annex A
    ('ISO27001', 'A.8.3',   'shadow_perms',        'Information access restriction'),
    ('ISO27001', 'A.8.3',   'passwd_perms',        'Information access restriction'),
    ('ISO27001', 'A.8.3',   'umask_secure',        'Information access restriction'),
    ('ISO27001', 'A.8.3',   'mac_enabled',         'Information access restriction'),
    ('ISO27001', 'A.8.3',   'selinux_enforcing',   'Information access restriction'),
    ('ISO27001', 'A.8.5',   'fail2ban_enabled',    'Secure authentication'),
    ('ISO27001', 'A.8.5',   'ssh_password_auth',   'Secure authentication'),
    ('ISO27001', 'A.8.5',   'password_min_length', 'Secure authentication'),
    ('ISO27001', 'A.8.5',   'password_max_days',   'Secure authentication'),
    ('ISO27001', 'A.8.5',   'account_lockout',     'Secure authentication'),
    ('ISO27001', 'A.8.8',   'auto_updates',        'Management of technical vulnerabilities'),
    ('ISO27001', 'A.8.15',  'auditd_enabled',      'Logging'),
    ('ISO27001', 'A.8.15',  'time_sync',           'Clock synchronization for logs'),
    ('ISO27001', 'A.8.18',  'ssh_root_login',      'Use of privileged utility programs'),
    ('ISO27001', 'A.8.20',  'firewall_enabled',    'Networks security'),
    ('ISO27001', 'A.8.20',  'ssh_protocol_2',      'Networks security'),
    ('ISO27001', 'A.8.20',  'telnet_closed',       'Networks security'),
    ('ISO27001', 'A.8.20',  'ftp_closed',          'Networks security'),
    ('ISO27001', 'A.8.20',  'rsh_closed',          'Networks security'),
    ('ISO27001', 'A.8.20',  'nis_closed',          'Networks security'),
    ('ISO27001', 'A.8.20',  'mysql_public',        'Networks security'),
    ('ISO27001', 'A.8.20',  'postgres_public',     'Networks security'),
    ('ISO27001', 'A.8.20',  'redis_public',        'Networks security'),
    ('ISO27001', 'A.8.20',  'nfs_disabled',        'Networks security'),

    -- GDPR (Article 32 — security of processing — is the primary technical anchor)
    ('GDPR', 'Art.32', 'firewall_enabled',     'Appropriate technical security measure'),
    ('GDPR', 'Art.32', 'auditd_enabled',       'Ability to ensure ongoing integrity and availability'),
    ('GDPR', 'Art.32', 'mysql_public',         'Resilience and confidentiality of processing systems'),
    ('GDPR', 'Art.32', 'postgres_public',      'Resilience and confidentiality of processing systems'),
    ('GDPR', 'Art.32', 'redis_public',         'Resilience and confidentiality of processing systems'),
    ('GDPR', 'Art.32', 'shadow_perms',         'Confidentiality of credentials'),
    ('GDPR', 'Art.32', 'ssh_protocol_2',       'Encryption of personal data in transit'),
    ('GDPR', 'Art.32', 'telnet_closed',        'Encryption of personal data in transit'),
    ('GDPR', 'Art.32', 'ftp_closed',           'Encryption of personal data in transit'),
    ('GDPR', 'Art.32', 'auto_updates',         'Process for testing and evaluating security measures'),
    ('GDPR', 'Art.25', 'selinux_enforcing',    'Data protection by design — secure defaults'),
    ('GDPR', 'Art.25', 'mac_enabled',          'Data protection by design — secure defaults'),
    ('GDPR', 'Art.25', 'umask_secure',         'Data protection by default — least privilege')
ON CONFLICT (framework, control_id, policy_rule_id) DO NOTHING;
