ALTER TABLE events ADD COLUMN IF NOT EXISTS schema_version SMALLINT AFTER ts;
ALTER TABLE events ADD COLUMN IF NOT EXISTS event_id VARCHAR(64) AFTER schema_version;
ALTER TABLE events ADD COLUMN IF NOT EXISTS raw_ref VARCHAR(512) AFTER event_id;
ALTER TABLE events ADD COLUMN IF NOT EXISTS collector VARCHAR(64) AFTER raw_ref;
ALTER TABLE events ADD COLUMN IF NOT EXISTS parser VARCHAR(64) AFTER collector;
ALTER TABLE events ADD COLUMN IF NOT EXISTS parser_status VARCHAR(32) AFTER parser;

ALTER TABLE web_requests ADD COLUMN IF NOT EXISTS schema_version SMALLINT AFTER ts;
ALTER TABLE web_requests ADD COLUMN IF NOT EXISTS event_id VARCHAR(64) AFTER schema_version;
ALTER TABLE web_requests ADD COLUMN IF NOT EXISTS raw_ref VARCHAR(512) AFTER event_id;
ALTER TABLE web_requests ADD COLUMN IF NOT EXISTS collector VARCHAR(64) AFTER raw_ref;
ALTER TABLE web_requests ADD COLUMN IF NOT EXISTS parser VARCHAR(64) AFTER collector;
ALTER TABLE web_requests ADD COLUMN IF NOT EXISTS parser_status VARCHAR(32) AFTER parser;
