//go:build windows

package logs

import (
    "bufio"
    "context"
    "errors"
    "os/exec"
    "strconv"
    "strings"
    "time"

    "github.com/CloudSpaceLab/control_one/internal/config"
    "go.uber.org/zap"
)

type eventLogCollector struct {
    cfg    config.LogSourceConfig
    logger *zap.Logger
}

func NewEventLogCollector(cfg config.LogSourceConfig, logger *zap.Logger) (Collector, error) {
    if len(cfg.EventChannels) == 0 && strings.TrimSpace(cfg.Program) == "" {
        return nil, errors.New("eventlog collector requires event_channels or program")
    }
    return &eventLogCollector{cfg: cfg, logger: logger}, nil
}

func (c *eventLogCollector) Run(ctx context.Context, out chan<- RawLog) error {
    channels := c.cfg.EventChannels
    if len(channels) == 0 {
        channels = []string{c.cfg.Program}
    }

    args := []string{"-NoProfile", "-Command"}
    script := buildPowerShellScript(channels)
    args = append(args, script)

    cmd := exec.CommandContext(ctx, "powershell.exe", args...)
    stdout, err := cmd.StdoutPipe()
    if err != nil {
        return err
    }
    stderr, err := cmd.StderrPipe()
    if err != nil {
        return err
    }

    if err := cmd.Start(); err != nil {
        return err
    }

    errCh := make(chan error, 2)

    go func() {
        scanner := bufio.NewScanner(stderr)
        for scanner.Scan() {
            c.logger.Debug("eventlog stderr", zap.String("line", scanner.Text()))
        }
        errCh <- scanner.Err()
    }()

    go func() {
        scanner := bufio.NewScanner(stdout)
        for scanner.Scan() {
            line := scanner.Text()
            evt := parseEventLogJSON(line)
            raw := RawLog{
                Timestamp: evt.Timestamp,
                Program:   evt.Provider,
                Source:    evt.Channel,
                Message:   evt.Message,
                Severity:  evt.Level,
                Hostname:  evt.Computer,
                Labels:    map[string]string{},
                Fields: map[string]any{
                    "event_id": evt.EventID,
                    "keywords": evt.Keywords,
                    "task":     evt.Task,
                },
            }
            for k, v := range c.cfg.Labels {
                raw.Labels[k] = v
            }
            select {
            case <-ctx.Done():
                errCh <- ctx.Err()
                return
            case out <- raw:
            }
        }
        if err := scanner.Err(); err != nil {
            errCh <- err
        } else {
            errCh <- cmd.Wait()
        }
    }()

    for i := 0; i < 2; i++ {
        if err := <-errCh; err != nil && !errors.Is(err, context.Canceled) {
            return err
        }
    }
    return nil
}

func buildPowerShellScript(channels []string) string {
    quoted := make([]string, 0, len(channels))
    for _, ch := range channels {
        ch = strings.TrimSpace(ch)
        if ch != "" {
            quoted = append(quoted, "'"+ch+"'")
        }
    }
    if len(quoted) == 0 {
        quoted = append(quoted, "'Application'")
    }
    // Use Get-WinEvent with -MaxEvents 0 -Wait for streaming
    return "while ($true) {" +
        "$channels = @(" + strings.Join(quoted, ",") + ");" +
        "foreach ($channel in $channels) {" +
        "$query = New-Object System.Diagnostics.Eventing.Reader.EventLogQuery($channel, [System.Diagnostics.Eventing.Reader.PathType]::LogName);" +
        "$reader = New-Object System.Diagnostics.Eventing.Reader.EventLogWatcher($query, $null, $true);" +
        "$reader.EventRecordWritten += { param($sender,$args) if ($args.EventRecord -ne $null) { $evt = $args.EventRecord; $data = @{ 'Timestamp' = $evt.TimeCreated.ToUniversalTime().ToString('o'); 'Provider' = $evt.ProviderName; 'Channel' = $evt.LogName; 'Message' = $evt.FormatDescription(); 'Level' = $evt.LevelDisplayName; 'EventID' = $evt.Id; 'Computer' = $evt.MachineName; 'Keywords' = $evt.KeywordsDisplayNames; 'Task' = $evt.TaskDisplayName }; Write-Output ($data | ConvertTo-Json -Compress) } };" +
        "$reader.Enabled = $true;" +
        "Register-ObjectEvent -InputObject $reader -EventName EventRecordWritten -SourceIdentifier (New-Guid).Guid | Out-Null;" +
        "}" +
        "Start-Sleep -Seconds 5" +
        "}"
}

type eventRecord struct {
    Timestamp time.Time
    Provider  string
    Channel   string
    Message   string
    Level     string
    EventID   int
    Computer  string
    Keywords  any
    Task      any
}

func parseEventLogJSON(line string) eventRecord {
    var evt eventRecord
    // Use very simple parsing: expect JSON objects with known keys
    // Since this is generated by ConvertTo-Json we can rely on strings.Split
    parts := strings.Split(line, ",")
    evt.Timestamp = time.Now().UTC()
    evt.Level = "info"
    for _, part := range parts {
        kv := strings.SplitN(part, ":", 2)
        if len(kv) != 2 {
            continue
        }
        key := strings.Trim(strings.Trim(kv[0], "{}\""), " ")
        value := strings.Trim(strings.Trim(kv[1], "{}\""), " ")
        switch key {
        case "Timestamp":
            if ts, err := time.Parse(time.RFC3339Nano, value); err == nil {
                evt.Timestamp = ts
            }
        case "Provider":
            evt.Provider = value
        case "Channel":
            evt.Channel = value
        case "Message":
            evt.Message = value
        case "Level":
            evt.Level = value
        case "EventID":
            if id, err := strconv.Atoi(strings.Trim(value, "\"")); err == nil {
                evt.EventID = id
            }
        case "Computer":
            evt.Computer = value
        }
    }
    return evt
}

func init() {
    RegisterCollectorFactory("eventlog", NewEventLogCollector)
}
